/**
 * OpenGL 1.3 API Descriptor (opengl32.dll)
 *
 * 335 gl* functions + 24 wgl* functions = 359 total exports.
 * All stdcall. GLdouble/GLclampd params use f64 (8 bytes on stack).
 * Signatures from the Khronos OpenGL 1.3 spec + the Win32 WGL ABI (opengl32.dll).
 */

import { ModuleDescriptor, FunctionDescriptor, ParameterDescriptor } from "./types";

const u = (name: string): ParameterDescriptor => ({ name, type: "u32" });
const i = (name: string): ParameterDescriptor => ({ name, type: "i32" });
const f = (name: string): ParameterDescriptor => ({ name, type: "f32" });
const d = (name: string): ParameterDescriptor => ({ name, type: "f64" });
const p = (name: string): ParameterDescriptor => ({ name, type: "ptr" });

const gl = (name: string, params: ParameterDescriptor[], returnType: "u32" | "void" = "void"): FunctionDescriptor => ({
    name,
    params,
    returnType,
    callingConvention: "stdcall",
});

export const opengl32Module: ModuleDescriptor = {
    name: "opengl32",
    functions: [
        // ===================== GL 1.0 =====================
        gl("glAccum", [u("op"), f("value")]),
        gl("glAlphaFunc", [u("func"), f("ref")]),
        gl("glBegin", [u("mode")]),
        gl("glBitmap", [i("width"), i("height"), f("xOrig"), f("yOrig"), f("xMove"), f("yMove"), p("bitmap")]),
        gl("glBlendFunc", [u("sfactor"), u("dfactor")]),
        gl("glCallList", [u("list")]),
        gl("glCallLists", [i("n"), u("type"), p("lists")]),
        gl("glClear", [u("mask")]),
        gl("glClearAccum", [f("red"), f("green"), f("blue"), f("alpha")]),
        gl("glClearColor", [f("red"), f("green"), f("blue"), f("alpha")]),
        gl("glClearDepth", [d("depth")]),
        gl("glClearIndex", [f("c")]),
        gl("glClearStencil", [i("s")]),
        gl("glClipPlane", [u("plane"), p("equation")]),
        gl("glColor3b", [i("red"), i("green"), i("blue")]),
        gl("glColor3bv", [p("v")]),
        gl("glColor3d", [d("red"), d("green"), d("blue")]),
        gl("glColor3dv", [p("v")]),
        gl("glColor3f", [f("red"), f("green"), f("blue")]),
        gl("glColor3fv", [p("v")]),
        gl("glColor3i", [i("red"), i("green"), i("blue")]),
        gl("glColor3iv", [p("v")]),
        gl("glColor3s", [i("red"), i("green"), i("blue")]),
        gl("glColor3sv", [p("v")]),
        gl("glColor3ub", [u("red"), u("green"), u("blue")]),
        gl("glColor3ubv", [p("v")]),
        gl("glColor3ui", [u("red"), u("green"), u("blue")]),
        gl("glColor3uiv", [p("v")]),
        gl("glColor3us", [u("red"), u("green"), u("blue")]),
        gl("glColor3usv", [p("v")]),
        gl("glColor4b", [i("red"), i("green"), i("blue"), i("alpha")]),
        gl("glColor4bv", [p("v")]),
        gl("glColor4d", [d("red"), d("green"), d("blue"), d("alpha")]),
        gl("glColor4dv", [p("v")]),
        gl("glColor4f", [f("red"), f("green"), f("blue"), f("alpha")]),
        gl("glColor4fv", [p("v")]),
        gl("glColor4i", [i("red"), i("green"), i("blue"), i("alpha")]),
        gl("glColor4iv", [p("v")]),
        gl("glColor4s", [i("red"), i("green"), i("blue"), i("alpha")]),
        gl("glColor4sv", [p("v")]),
        gl("glColor4ub", [u("red"), u("green"), u("blue"), u("alpha")]),
        gl("glColor4ubv", [p("v")]),
        gl("glColor4ui", [u("red"), u("green"), u("blue"), u("alpha")]),
        gl("glColor4uiv", [p("v")]),
        gl("glColor4us", [u("red"), u("green"), u("blue"), u("alpha")]),
        gl("glColor4usv", [p("v")]),
        gl("glColorMask", [u("red"), u("green"), u("blue"), u("alpha")]),
        gl("glColorMaterial", [u("face"), u("mode")]),
        gl("glCopyPixels", [i("x"), i("y"), i("width"), i("height"), u("type")]),
        gl("glCullFace", [u("mode")]),
        gl("glDeleteLists", [u("list"), i("range")]),
        gl("glDepthFunc", [u("func")]),
        gl("glDepthMask", [u("flag")]),
        gl("glDepthRange", [d("zNear"), d("zFar")]),
        gl("glDisable", [u("cap")]),
        gl("glDrawBuffer", [u("mode")]),
        gl("glDrawPixels", [i("width"), i("height"), u("format"), u("type"), p("pixels")]),
        gl("glEdgeFlag", [u("flag")]),
        gl("glEdgeFlagv", [p("flag")]),
        gl("glEnable", [u("cap")]),
        gl("glEnd", []),
        gl("glEndList", []),
        gl("glEvalCoord1d", [d("u")]),
        gl("glEvalCoord1dv", [p("u")]),
        gl("glEvalCoord1f", [f("u")]),
        gl("glEvalCoord1fv", [p("u")]),
        gl("glEvalCoord2d", [d("u"), d("v")]),
        gl("glEvalCoord2dv", [p("u")]),
        gl("glEvalCoord2f", [f("u"), f("v")]),
        gl("glEvalCoord2fv", [p("u")]),
        gl("glEvalMesh1", [u("mode"), i("i1"), i("i2")]),
        gl("glEvalMesh2", [u("mode"), i("i1"), i("i2"), i("j1"), i("j2")]),
        gl("glEvalPoint1", [i("i")]),
        gl("glEvalPoint2", [i("i"), i("j")]),
        gl("glFeedbackBuffer", [i("size"), u("type"), p("buffer")]),
        gl("glFinish", []),
        gl("glFlush", []),
        gl("glFogf", [u("pname"), f("param")]),
        gl("glFogfv", [u("pname"), p("params")]),
        gl("glFogi", [u("pname"), i("param")]),
        gl("glFogiv", [u("pname"), p("params")]),
        gl("glFrontFace", [u("mode")]),
        gl("glFrustum", [d("left"), d("right"), d("bottom"), d("top"), d("zNear"), d("zFar")]),
        gl("glGenLists", [i("range")], "u32"),
        gl("glGetBooleanv", [u("pname"), p("params")]),
        gl("glGetClipPlane", [u("plane"), p("equation")]),
        gl("glGetDoublev", [u("pname"), p("params")]),
        gl("glGetError", [], "u32"),
        gl("glGetFloatv", [u("pname"), p("params")]),
        gl("glGetIntegerv", [u("pname"), p("params")]),
        gl("glGetLightfv", [u("light"), u("pname"), p("params")]),
        gl("glGetLightiv", [u("light"), u("pname"), p("params")]),
        gl("glGetMapdv", [u("target"), u("query"), p("v")]),
        gl("glGetMapfv", [u("target"), u("query"), p("v")]),
        gl("glGetMapiv", [u("target"), u("query"), p("v")]),
        gl("glGetMaterialfv", [u("face"), u("pname"), p("params")]),
        gl("glGetMaterialiv", [u("face"), u("pname"), p("params")]),
        gl("glGetPixelMapfv", [u("map"), p("values")]),
        gl("glGetPixelMapuiv", [u("map"), p("values")]),
        gl("glGetPixelMapusv", [u("map"), p("values")]),
        gl("glGetPolygonStipple", [p("mask")]),
        gl("glGetString", [u("name")], "u32"),
        gl("glGetTexEnvfv", [u("target"), u("pname"), p("params")]),
        gl("glGetTexEnviv", [u("target"), u("pname"), p("params")]),
        gl("glGetTexGendv", [u("coord"), u("pname"), p("params")]),
        gl("glGetTexGenfv", [u("coord"), u("pname"), p("params")]),
        gl("glGetTexGeniv", [u("coord"), u("pname"), p("params")]),
        gl("glGetTexImage", [u("target"), i("level"), u("format"), u("type"), p("pixels")]),
        gl("glGetTexLevelParameterfv", [u("target"), i("level"), u("pname"), p("params")]),
        gl("glGetTexLevelParameteriv", [u("target"), i("level"), u("pname"), p("params")]),
        gl("glGetTexParameterfv", [u("target"), u("pname"), p("params")]),
        gl("glGetTexParameteriv", [u("target"), u("pname"), p("params")]),
        gl("glHint", [u("target"), u("mode")]),
        gl("glIndexMask", [u("mask")]),
        gl("glIndexd", [d("c")]),
        gl("glIndexdv", [p("c")]),
        gl("glIndexf", [f("c")]),
        gl("glIndexfv", [p("c")]),
        gl("glIndexi", [i("c")]),
        gl("glIndexiv", [p("c")]),
        gl("glIndexs", [i("c")]),
        gl("glIndexsv", [p("c")]),
        gl("glIndexub", [u("c")]),
        gl("glIndexubv", [p("c")]),
        gl("glInitNames", []),
        gl("glIsEnabled", [u("cap")], "u32"),
        gl("glIsList", [u("list")], "u32"),
        gl("glLightModelf", [u("pname"), f("param")]),
        gl("glLightModelfv", [u("pname"), p("params")]),
        gl("glLightModeli", [u("pname"), i("param")]),
        gl("glLightModeliv", [u("pname"), p("params")]),
        gl("glLightf", [u("light"), u("pname"), f("param")]),
        gl("glLightfv", [u("light"), u("pname"), p("params")]),
        gl("glLighti", [u("light"), u("pname"), i("param")]),
        gl("glLightiv", [u("light"), u("pname"), p("params")]),
        gl("glLineStipple", [i("factor"), u("pattern")]),
        gl("glLineWidth", [f("width")]),
        gl("glListBase", [u("base")]),
        gl("glLoadIdentity", []),
        gl("glLoadMatrixd", [p("m")]),
        gl("glLoadMatrixf", [p("m")]),
        gl("glLoadName", [u("name")]),
        gl("glLogicOp", [u("opcode")]),
        gl("glMap1d", [u("target"), d("u1"), d("u2"), i("stride"), i("order"), p("points")]),
        gl("glMap1f", [u("target"), f("u1"), f("u2"), i("stride"), i("order"), p("points")]),
        gl("glMap2d", [u("target"), d("u1"), d("u2"), i("ustride"), i("uorder"), d("v1"), d("v2"), i("vstride"), i("vorder"), p("points")]),
        gl("glMap2f", [u("target"), f("u1"), f("u2"), i("ustride"), i("uorder"), f("v1"), f("v2"), i("vstride"), i("vorder"), p("points")]),
        gl("glMapGrid1d", [i("un"), d("u1"), d("u2")]),
        gl("glMapGrid1f", [i("un"), f("u1"), f("u2")]),
        gl("glMapGrid2d", [i("un"), d("u1"), d("u2"), i("vn"), d("v1"), d("v2")]),
        gl("glMapGrid2f", [i("un"), f("u1"), f("u2"), i("vn"), f("v1"), f("v2")]),
        gl("glMaterialf", [u("face"), u("pname"), f("param")]),
        gl("glMaterialfv", [u("face"), u("pname"), p("params")]),
        gl("glMateriali", [u("face"), u("pname"), i("param")]),
        gl("glMaterialiv", [u("face"), u("pname"), p("params")]),
        gl("glMatrixMode", [u("mode")]),
        gl("glMultMatrixd", [p("m")]),
        gl("glMultMatrixf", [p("m")]),
        gl("glNewList", [u("list"), u("mode")]),
        gl("glNormal3b", [i("nx"), i("ny"), i("nz")]),
        gl("glNormal3bv", [p("v")]),
        gl("glNormal3d", [d("nx"), d("ny"), d("nz")]),
        gl("glNormal3dv", [p("v")]),
        gl("glNormal3f", [f("nx"), f("ny"), f("nz")]),
        gl("glNormal3fv", [p("v")]),
        gl("glNormal3i", [i("nx"), i("ny"), i("nz")]),
        gl("glNormal3iv", [p("v")]),
        gl("glNormal3s", [i("nx"), i("ny"), i("nz")]),
        gl("glNormal3sv", [p("v")]),
        gl("glOrtho", [d("left"), d("right"), d("bottom"), d("top"), d("zNear"), d("zFar")]),
        gl("glPassThrough", [f("token")]),
        gl("glPixelMapfv", [u("map"), i("mapsize"), p("values")]),
        gl("glPixelMapuiv", [u("map"), i("mapsize"), p("values")]),
        gl("glPixelMapusv", [u("map"), i("mapsize"), p("values")]),
        gl("glPixelStoref", [u("pname"), f("param")]),
        gl("glPixelStorei", [u("pname"), i("param")]),
        gl("glPixelTransferf", [u("pname"), f("param")]),
        gl("glPixelTransferi", [u("pname"), i("param")]),
        gl("glPixelZoom", [f("xfactor"), f("yfactor")]),
        gl("glPointSize", [f("size")]),
        gl("glPolygonMode", [u("face"), u("mode")]),
        gl("glPolygonStipple", [p("mask")]),
        gl("glPopAttrib", []),
        gl("glPopMatrix", []),
        gl("glPopName", []),
        gl("glPrioritizeTextures", [i("n"), p("textures"), p("priorities")]),
        gl("glPushAttrib", [u("mask")]),
        gl("glPushMatrix", []),
        gl("glPushName", [u("name")]),
        gl("glRasterPos2d", [d("x"), d("y")]),
        gl("glRasterPos2dv", [p("v")]),
        gl("glRasterPos2f", [f("x"), f("y")]),
        gl("glRasterPos2fv", [p("v")]),
        gl("glRasterPos2i", [i("x"), i("y")]),
        gl("glRasterPos2iv", [p("v")]),
        gl("glRasterPos2s", [i("x"), i("y")]),
        gl("glRasterPos2sv", [p("v")]),
        gl("glRasterPos3d", [d("x"), d("y"), d("z")]),
        gl("glRasterPos3dv", [p("v")]),
        gl("glRasterPos3f", [f("x"), f("y"), f("z")]),
        gl("glRasterPos3fv", [p("v")]),
        gl("glRasterPos3i", [i("x"), i("y"), i("z")]),
        gl("glRasterPos3iv", [p("v")]),
        gl("glRasterPos3s", [i("x"), i("y"), i("z")]),
        gl("glRasterPos3sv", [p("v")]),
        gl("glRasterPos4d", [d("x"), d("y"), d("z"), d("w")]),
        gl("glRasterPos4dv", [p("v")]),
        gl("glRasterPos4f", [f("x"), f("y"), f("z"), f("w")]),
        gl("glRasterPos4fv", [p("v")]),
        gl("glRasterPos4i", [i("x"), i("y"), i("z"), i("w")]),
        gl("glRasterPos4iv", [p("v")]),
        gl("glRasterPos4s", [i("x"), i("y"), i("z"), i("w")]),
        gl("glRasterPos4sv", [p("v")]),
        gl("glReadBuffer", [u("mode")]),
        gl("glReadPixels", [i("x"), i("y"), i("width"), i("height"), u("format"), u("type"), p("pixels")]),
        gl("glRectd", [d("x1"), d("y1"), d("x2"), d("y2")]),
        gl("glRectdv", [p("v1"), p("v2")]),
        gl("glRectf", [f("x1"), f("y1"), f("x2"), f("y2")]),
        gl("glRectfv", [p("v1"), p("v2")]),
        gl("glRecti", [i("x1"), i("y1"), i("x2"), i("y2")]),
        gl("glRectiv", [p("v1"), p("v2")]),
        gl("glRects", [i("x1"), i("y1"), i("x2"), i("y2")]),
        gl("glRectsv", [p("v1"), p("v2")]),
        gl("glRenderMode", [u("mode")], "u32"),
        gl("glRotated", [d("angle"), d("x"), d("y"), d("z")]),
        gl("glRotatef", [f("angle"), f("x"), f("y"), f("z")]),
        gl("glScaled", [d("x"), d("y"), d("z")]),
        gl("glScalef", [f("x"), f("y"), f("z")]),
        gl("glScissor", [i("x"), i("y"), i("width"), i("height")]),
        gl("glSelectBuffer", [i("size"), p("buffer")]),
        gl("glShadeModel", [u("mode")]),
        gl("glStencilFunc", [u("func"), i("ref"), u("mask")]),
        gl("glStencilMask", [u("mask")]),
        gl("glStencilOp", [u("fail"), u("zfail"), u("zpass")]),
        gl("glTexCoord1d", [d("s")]),
        gl("glTexCoord1dv", [p("v")]),
        gl("glTexCoord1f", [f("s")]),
        gl("glTexCoord1fv", [p("v")]),
        gl("glTexCoord1i", [i("s")]),
        gl("glTexCoord1iv", [p("v")]),
        gl("glTexCoord1s", [i("s")]),
        gl("glTexCoord1sv", [p("v")]),
        gl("glTexCoord2d", [d("s"), d("t")]),
        gl("glTexCoord2dv", [p("v")]),
        gl("glTexCoord2f", [f("s"), f("t")]),
        gl("glTexCoord2fv", [p("v")]),
        gl("glTexCoord2i", [i("s"), i("t")]),
        gl("glTexCoord2iv", [p("v")]),
        gl("glTexCoord2s", [i("s"), i("t")]),
        gl("glTexCoord2sv", [p("v")]),
        gl("glTexCoord3d", [d("s"), d("t"), d("r")]),
        gl("glTexCoord3dv", [p("v")]),
        gl("glTexCoord3f", [f("s"), f("t"), f("r")]),
        gl("glTexCoord3fv", [p("v")]),
        gl("glTexCoord3i", [i("s"), i("t"), i("r")]),
        gl("glTexCoord3iv", [p("v")]),
        gl("glTexCoord3s", [i("s"), i("t"), i("r")]),
        gl("glTexCoord3sv", [p("v")]),
        gl("glTexCoord4d", [d("s"), d("t"), d("r"), d("q")]),
        gl("glTexCoord4dv", [p("v")]),
        gl("glTexCoord4f", [f("s"), f("t"), f("r"), f("q")]),
        gl("glTexCoord4fv", [p("v")]),
        gl("glTexCoord4i", [i("s"), i("t"), i("r"), i("q")]),
        gl("glTexCoord4iv", [p("v")]),
        gl("glTexCoord4s", [i("s"), i("t"), i("r"), i("q")]),
        gl("glTexCoord4sv", [p("v")]),
        gl("glTexEnvf", [u("target"), u("pname"), f("param")]),
        gl("glTexEnvfv", [u("target"), u("pname"), p("params")]),
        gl("glTexEnvi", [u("target"), u("pname"), i("param")]),
        gl("glTexEnviv", [u("target"), u("pname"), p("params")]),
        gl("glTexGend", [u("coord"), u("pname"), d("param")]),
        gl("glTexGendv", [u("coord"), u("pname"), p("params")]),
        gl("glTexGenf", [u("coord"), u("pname"), f("param")]),
        gl("glTexGenfv", [u("coord"), u("pname"), p("params")]),
        gl("glTexGeni", [u("coord"), u("pname"), i("param")]),
        gl("glTexGeniv", [u("coord"), u("pname"), p("params")]),
        gl("glTexImage1D", [u("target"), i("level"), i("internalformat"), i("width"), i("border"), u("format"), u("type"), p("pixels")]),
        gl("glTexImage2D", [u("target"), i("level"), i("internalformat"), i("width"), i("height"), i("border"), u("format"), u("type"), p("pixels")]),
        gl("glTexParameterf", [u("target"), u("pname"), f("param")]),
        gl("glTexParameterfv", [u("target"), u("pname"), p("params")]),
        gl("glTexParameteri", [u("target"), u("pname"), i("param")]),
        gl("glTexParameteriv", [u("target"), u("pname"), p("params")]),
        gl("glTexSubImage1D", [u("target"), i("level"), i("xoffset"), i("width"), u("format"), u("type"), p("pixels")]),
        gl("glTexSubImage2D", [u("target"), i("level"), i("xoffset"), i("yoffset"), i("width"), i("height"), u("format"), u("type"), p("pixels")]),
        gl("glTranslated", [d("x"), d("y"), d("z")]),
        gl("glTranslatef", [f("x"), f("y"), f("z")]),
        gl("glVertex2d", [d("x"), d("y")]),
        gl("glVertex2dv", [p("v")]),
        gl("glVertex2f", [f("x"), f("y")]),
        gl("glVertex2fv", [p("v")]),
        gl("glVertex2i", [i("x"), i("y")]),
        gl("glVertex2iv", [p("v")]),
        gl("glVertex2s", [i("x"), i("y")]),
        gl("glVertex2sv", [p("v")]),
        gl("glVertex3d", [d("x"), d("y"), d("z")]),
        gl("glVertex3dv", [p("v")]),
        gl("glVertex3f", [f("x"), f("y"), f("z")]),
        gl("glVertex3fv", [p("v")]),
        gl("glVertex3i", [i("x"), i("y"), i("z")]),
        gl("glVertex3iv", [p("v")]),
        gl("glVertex3s", [i("x"), i("y"), i("z")]),
        gl("glVertex3sv", [p("v")]),
        gl("glVertex4d", [d("x"), d("y"), d("z"), d("w")]),
        gl("glVertex4dv", [p("v")]),
        gl("glVertex4f", [f("x"), f("y"), f("z"), f("w")]),
        gl("glVertex4fv", [p("v")]),
        gl("glVertex4i", [i("x"), i("y"), i("z"), i("w")]),
        gl("glVertex4iv", [p("v")]),
        gl("glVertex4s", [i("x"), i("y"), i("z"), i("w")]),
        gl("glVertex4sv", [p("v")]),
        gl("glViewport", [i("x"), i("y"), i("width"), i("height")]),

        // ===================== GL 1.1 =====================
        gl("glAreTexturesResident", [i("n"), p("textures"), p("residences")], "u32"),
        gl("glArrayElement", [i("i")]),
        gl("glBindTexture", [u("target"), u("texture")]),
        gl("glColorPointer", [i("size"), u("type"), i("stride"), p("pointer")]),
        gl("glCopyTexImage1D", [u("target"), i("level"), u("internalFormat"), i("x"), i("y"), i("width"), i("border")]),
        gl("glCopyTexImage2D", [u("target"), i("level"), u("internalFormat"), i("x"), i("y"), i("width"), i("height"), i("border")]),
        gl("glCopyTexSubImage1D", [u("target"), i("level"), i("xoffset"), i("x"), i("y"), i("width")]),
        gl("glCopyTexSubImage2D", [u("target"), i("level"), i("xoffset"), i("yoffset"), i("x"), i("y"), i("width"), i("height")]),
        gl("glDeleteTextures", [i("n"), p("textures")]),
        gl("glDisableClientState", [u("cap")]),
        gl("glDrawArrays", [u("mode"), i("first"), i("count")]),
        gl("glDrawElements", [u("mode"), i("count"), u("type"), p("indices")]),
        gl("glEdgeFlagPointer", [i("stride"), p("pointer")]),
        gl("glEnableClientState", [u("cap")]),
        gl("glGenTextures", [i("n"), p("textures")]),
        gl("glGetPointerv", [u("pname"), p("params")]),
        gl("glIsTexture", [u("texture")], "u32"),
        gl("glIndexPointer", [u("type"), i("stride"), p("pointer")]),
        gl("glInterleavedArrays", [u("format"), i("stride"), p("pointer")]),
        gl("glNormalPointer", [u("type"), i("stride"), p("pointer")]),
        gl("glPolygonOffset", [f("factor"), f("units")]),
        gl("glPopClientAttrib", []),
        gl("glPushClientAttrib", [u("mask")]),
        gl("glTexCoordPointer", [i("size"), u("type"), i("stride"), p("pointer")]),
        gl("glVertexPointer", [i("size"), u("type"), i("stride"), p("pointer")]),

        // ===================== GL 1.2 =====================
        gl("glDrawRangeElements", [u("mode"), u("start"), u("end"), i("count"), u("type"), p("indices")]),
        gl("glTexImage3D", [u("target"), i("level"), i("internalFormat"), i("width"), i("height"), i("depth"), i("border"), u("format"), u("type"), p("data")]),
        gl("glTexSubImage3D", [u("target"), i("level"), i("xoffset"), i("yoffset"), i("zoffset"), i("width"), i("height"), i("depth"), u("format"), u("type"), p("pixels")]),
        gl("glCopyTexSubImage3D", [u("target"), i("level"), i("xoffset"), i("yoffset"), i("zoffset"), i("x"), i("y"), i("width"), i("height")]),

        // ===================== GL 1.3 =====================
        gl("glActiveTexture", [u("texture")]),
        gl("glSampleCoverage", [f("value"), u("invert")]),
        gl("glCompressedTexImage3D", [u("target"), i("level"), u("internalformat"), i("width"), i("height"), i("depth"), i("border"), i("imageSize"), p("data")]),
        gl("glCompressedTexImage2D", [u("target"), i("level"), u("internalformat"), i("width"), i("height"), i("border"), i("imageSize"), p("data")]),
        gl("glCompressedTexImage1D", [u("target"), i("level"), u("internalformat"), i("width"), i("border"), i("imageSize"), p("data")]),
        gl("glCompressedTexSubImage3D", [u("target"), i("level"), i("xoffset"), i("yoffset"), i("zoffset"), i("width"), i("height"), i("depth"), u("format"), i("imageSize"), p("data")]),
        gl("glCompressedTexSubImage2D", [u("target"), i("level"), i("xoffset"), i("yoffset"), i("width"), i("height"), u("format"), i("imageSize"), p("data")]),
        gl("glCompressedTexSubImage1D", [u("target"), i("level"), i("xoffset"), i("width"), u("format"), i("imageSize"), p("data")]),
        gl("glGetCompressedTexImage", [u("target"), i("level"), p("pixels")]),
        gl("glClientActiveTexture", [u("texture")]),
        gl("glMultiTexCoord1d", [u("target"), d("s")]),
        gl("glMultiTexCoord1dv", [u("target"), p("v")]),
        gl("glMultiTexCoord1f", [u("target"), f("s")]),
        gl("glMultiTexCoord1fv", [u("target"), p("v")]),
        gl("glMultiTexCoord1i", [u("target"), i("s")]),
        gl("glMultiTexCoord1iv", [u("target"), p("v")]),
        gl("glMultiTexCoord1s", [u("target"), i("s")]),
        gl("glMultiTexCoord1sv", [u("target"), p("v")]),
        gl("glMultiTexCoord2d", [u("target"), d("s"), d("t")]),
        gl("glMultiTexCoord2dv", [u("target"), p("v")]),
        gl("glMultiTexCoord2f", [u("target"), f("s"), f("t")]),
        gl("glMultiTexCoord2fv", [u("target"), p("v")]),
        gl("glMultiTexCoord2i", [u("target"), i("s"), i("t")]),
        gl("glMultiTexCoord2iv", [u("target"), p("v")]),
        gl("glMultiTexCoord2s", [u("target"), i("s"), i("t")]),
        gl("glMultiTexCoord2sv", [u("target"), p("v")]),
        gl("glMultiTexCoord3d", [u("target"), d("s"), d("t"), d("r")]),
        gl("glMultiTexCoord3dv", [u("target"), p("v")]),
        gl("glMultiTexCoord3f", [u("target"), f("s"), f("t"), f("r")]),
        gl("glMultiTexCoord3fv", [u("target"), p("v")]),
        gl("glMultiTexCoord3i", [u("target"), i("s"), i("t"), i("r")]),
        gl("glMultiTexCoord3iv", [u("target"), p("v")]),
        gl("glMultiTexCoord3s", [u("target"), i("s"), i("t"), i("r")]),
        gl("glMultiTexCoord3sv", [u("target"), p("v")]),
        gl("glMultiTexCoord4d", [u("target"), d("s"), d("t"), d("r"), d("q")]),
        gl("glMultiTexCoord4dv", [u("target"), p("v")]),
        gl("glMultiTexCoord4f", [u("target"), f("s"), f("t"), f("r"), f("q")]),
        gl("glMultiTexCoord4fv", [u("target"), p("v")]),
        gl("glMultiTexCoord4i", [u("target"), i("s"), i("t"), i("r"), i("q")]),
        gl("glMultiTexCoord4iv", [u("target"), p("v")]),
        gl("glMultiTexCoord4s", [u("target"), i("s"), i("t"), i("r"), i("q")]),
        gl("glMultiTexCoord4sv", [u("target"), p("v")]),
        gl("glLoadTransposeMatrixf", [p("m")]),
        gl("glLoadTransposeMatrixd", [p("m")]),
        gl("glMultTransposeMatrixf", [p("m")]),
        gl("glMultTransposeMatrixd", [p("m")]),

        // ===================== Extensions =====================
        gl("glLockArraysEXT", [i("first"), i("count")]),
        gl("glUnlockArraysEXT", []),

        // ARB multitexture aliases (wglGetProcAddress returns these)
        gl("glActiveTextureARB", [u("texture")]),
        gl("glClientActiveTextureARB", [u("texture")]),
        gl("glMultiTexCoord2fARB", [u("target"), f("s"), f("t")]),
        gl("glMultiTexCoord2fvARB", [u("target"), p("v")]),
        gl("glMultiTexCoord4fARB", [u("target"), f("s"), f("t"), f("r"), f("q")]),
        gl("glMultiTexCoord4fvARB", [u("target"), p("v")]),

        // ===================== WGL =====================
        gl("wglChoosePixelFormat", [u("hdc"), p("ppfd")], "u32"),
        gl("wglCopyContext", [u("src"), u("dst"), u("mask")], "u32"),
        gl("wglCreateContext", [u("hdc")], "u32"),
        gl("wglCreateLayerContext", [u("hdc"), i("layerPlane")], "u32"),
        gl("wglDeleteContext", [u("hglrc")], "u32"),
        gl("wglDescribeLayerPlane", [u("hdc"), i("pixelFormat"), i("layerPlane"), u("nBytes"), p("plpd")], "u32"),
        gl("wglDescribePixelFormat", [u("hdc"), i("pixelFormat"), u("nBytes"), p("ppfd")], "u32"),
        gl("wglGetCurrentContext", [], "u32"),
        gl("wglGetCurrentDC", [], "u32"),
        gl("wglGetLayerPaletteEntries", [u("hdc"), i("layerPlane"), i("start"), i("entries"), p("cr")], "u32"),
        gl("wglGetPixelFormat", [u("hdc")], "u32"),
        gl("wglGetProcAddress", [p("name")], "u32"),
        gl("wglMakeCurrent", [u("hdc"), u("hglrc")], "u32"),
        gl("wglRealizeLayerPalette", [u("hdc"), i("layerPlane"), u("realize")], "u32"),
        gl("wglSetLayerPaletteEntries", [u("hdc"), i("layerPlane"), i("start"), i("entries"), p("cr")], "u32"),
        gl("wglSetPixelFormat", [u("hdc"), i("format"), p("ppfd")], "u32"),
        gl("wglShareLists", [u("hglrc1"), u("hglrc2")], "u32"),
        gl("wglSwapBuffers", [u("hdc")], "u32"),
        gl("wglSwapLayerBuffers", [u("hdc"), u("planes")], "u32"),
        gl("wglUseFontBitmapsA", [u("hdc"), u("first"), u("count"), u("listBase")], "u32"),
        gl("wglUseFontBitmapsW", [u("hdc"), u("first"), u("count"), u("listBase")], "u32"),
        gl("wglUseFontOutlinesA", [u("hdc"), u("first"), u("count"), u("listBase"), f("deviation"), f("extrusion"), i("format"), p("pgmf")], "u32"),
        gl("wglUseFontOutlinesW", [u("hdc"), u("first"), u("count"), u("listBase"), f("deviation"), f("extrusion"), i("format"), p("pgmf")], "u32"),

        // WGL extensions
        gl("wglSetDeviceGammaRamp", [u("hdc"), p("ramp")], "u32"),
        gl("wglGetDeviceGammaRamp", [u("hdc"), p("ramp")], "u32"),
        gl("wglGetExtensionsStringARB", [u("hdc")], "u32"),
    ]
};
