// Argument counts (32-bit stack slots) for common stdcall Win32 functions, used to keep the
// guest stack balanced when an unimplemented import is called (tracing stubs). Only stdcall
// functions matter here: cdecl callers clean up themselves.
export const SIGNATURES = {
  // kernel32
  AddAtomA: 1, AddAtomW: 1, AreFileApisANSI: 0, Beep: 2, CancelIo: 1, CompareFileTime: 2, CompareStringA: 6, CompareStringW: 6,
  ConnectNamedPipe: 2, ContinueDebugEvent: 3, CopyFileA: 3, CopyFileW: 3, CreateDirectoryA: 2, CreateDirectoryW: 2, CreateEventA: 4, CreateEventW: 4,
  CreateFileA: 7, CreateFileW: 7, CreateFileMappingA: 6, CreateFileMappingW: 6, CreateMutexA: 3, CreateMutexW: 3, CreatePipe: 4,
  CreateProcessA: 10, CreateProcessW: 10, CreateSemaphoreA: 4, CreateSemaphoreW: 4, CreateThread: 6, CreateWaitableTimerA: 3,
  DebugBreak: 0, DeleteCriticalSection: 1, DeleteFileA: 1, DeleteFileW: 1, DeviceIoControl: 8, DisableThreadLibraryCalls: 1,
  DuplicateHandle: 7, EnterCriticalSection: 1, ExitProcess: 1, ExitThread: 1, ExpandEnvironmentStringsA: 3, FatalAppExitA: 2,
  FileTimeToDosDateTime: 3, FileTimeToLocalFileTime: 2, FileTimeToSystemTime: 2, FindClose: 1, FindFirstFileA: 2, FindFirstFileW: 2,
  FindNextFileA: 2, FindNextFileW: 2, FindResourceA: 3, FindResourceW: 3, FindResourceExA: 4, FlushFileBuffers: 1, FlushInstructionCache: 3,
  FormatMessageA: 7, FormatMessageW: 7, FreeEnvironmentStringsA: 1, FreeEnvironmentStringsW: 1, FreeLibrary: 1, FreeResource: 1,
  GetACP: 0, GetCPInfo: 2, GetCommandLineA: 0, GetCommandLineW: 0, GetComputerNameA: 2, GetConsoleCP: 0, GetConsoleMode: 2, GetConsoleOutputCP: 0,
  GetCurrentDirectoryA: 2, GetCurrentDirectoryW: 2, GetCurrentProcess: 0, GetCurrentProcessId: 0, GetCurrentThread: 0, GetCurrentThreadId: 0,
  GetDateFormatA: 6, GetDiskFreeSpaceA: 5, GetDiskFreeSpaceExA: 4, GetDriveTypeA: 1, GetEnvironmentStrings: 0, GetEnvironmentStringsW: 0,
  GetEnvironmentVariableA: 3, GetEnvironmentVariableW: 3, GetExitCodeProcess: 2, GetExitCodeThread: 2, GetFileAttributesA: 1, GetFileAttributesW: 1,
  GetFileAttributesExA: 3, GetFileInformationByHandle: 2, GetFileSize: 2, GetFileSizeEx: 2, GetFileTime: 4, GetFileType: 1, GetFullPathNameA: 4, GetFullPathNameW: 4,
  GetLastError: 0, GetLocalTime: 1, GetLocaleInfoA: 4, GetLocaleInfoW: 4, GetLogicalDrives: 0, GetLogicalDriveStringsA: 2, GetLongPathNameA: 3,
  GetModuleFileNameA: 3, GetModuleFileNameW: 3, GetModuleHandleA: 1, GetModuleHandleW: 1, GetModuleHandleExA: 3, GetOEMCP: 0, GetOverlappedResult: 4,
  GetPriorityClass: 1, GetPrivateProfileIntA: 4, GetPrivateProfileStringA: 6, GetProcAddress: 2, GetProcessAffinityMask: 3, GetProcessHeap: 0,
  GetProcessTimes: 5, GetProcessVersion: 1, GetProcessWorkingSetSize: 3, GetShortPathNameA: 3, GetStartupInfoA: 1, GetStartupInfoW: 1, GetStdHandle: 1,
  GetStringTypeA: 5, GetStringTypeW: 4, GetStringTypeExA: 5, GetSystemDefaultLCID: 0, GetSystemDefaultLangID: 0, GetSystemDirectoryA: 2, GetSystemDirectoryW: 2,
  GetSystemInfo: 1, GetSystemTime: 1, GetSystemTimeAsFileTime: 1, GetTempFileNameA: 4, GetTempPathA: 2, GetTempPathW: 2, GetThreadContext: 2, GetThreadLocale: 0,
  GetThreadPriority: 1, GetThreadTimes: 5, GetTickCount: 0, GetTimeFormatA: 6, GetTimeZoneInformation: 1, GetUserDefaultLCID: 0, GetUserDefaultLangID: 0,
  GetVersion: 0, GetVersionExA: 1, GetVersionExW: 1, GetVolumeInformationA: 8, GetWindowsDirectoryA: 2, GetWindowsDirectoryW: 2, GlobalAlloc: 2, GlobalFlags: 1,
  GlobalFree: 1, GlobalHandle: 1, GlobalLock: 1, GlobalMemoryStatus: 1, GlobalMemoryStatusEx: 1, GlobalReAlloc: 3, GlobalSize: 1, GlobalUnlock: 1,
  HeapAlloc: 3, HeapCompact: 2, HeapCreate: 3, HeapDestroy: 1, HeapFree: 3, HeapReAlloc: 4, HeapSize: 3, HeapValidate: 3, HeapWalk: 2,
  InitializeCriticalSection: 1, InitializeCriticalSectionAndSpinCount: 2, InterlockedCompareExchange: 3, InterlockedDecrement: 1, InterlockedExchange: 2,
  InterlockedExchangeAdd: 2, InterlockedIncrement: 1, IsBadCodePtr: 1, IsBadReadPtr: 2, IsBadStringPtrA: 2, IsBadWritePtr: 2, IsDBCSLeadByte: 1,
  IsDBCSLeadByteEx: 2, IsDebuggerPresent: 0, IsProcessorFeaturePresent: 1, IsValidCodePage: 1, IsValidLocale: 2, LCMapStringA: 6, LCMapStringW: 6,
  LeaveCriticalSection: 1, LoadLibraryA: 1, LoadLibraryW: 1, LoadLibraryExA: 3, LoadLibraryExW: 3, LoadResource: 2, LocalAlloc: 2, LocalFileTimeToFileTime: 2,
  LocalFree: 1, LocalLock: 1, LocalReAlloc: 3, LocalSize: 1, LocalUnlock: 1, LockFile: 5, LockResource: 1, MapViewOfFile: 5, MoveFileA: 2, MoveFileExA: 3,
  MulDiv: 3, MultiByteToWideChar: 6, OpenEventA: 3, OpenFile: 3, OpenMutexA: 3, OpenProcess: 3, OutputDebugStringA: 1, OutputDebugStringW: 1,
  PeekNamedPipe: 6, PulseEvent: 1, QueryPerformanceCounter: 1, QueryPerformanceFrequency: 1, RaiseException: 4, ReadFile: 5, ReadProcessMemory: 5,
  ReleaseMutex: 1, ReleaseSemaphore: 3, RemoveDirectoryA: 1, ResetEvent: 1, ResumeThread: 1, RtlUnwind: 4, SearchPathA: 6, SetConsoleCtrlHandler: 2,
  SetCurrentDirectoryA: 1, SetCurrentDirectoryW: 1, SetEndOfFile: 1, SetEnvironmentVariableA: 2, SetEnvironmentVariableW: 2, SetErrorMode: 1, SetEvent: 1,
  SetFileAttributesA: 2, SetFilePointer: 4, SetFilePointerEx: 5, SetFileTime: 4, SetHandleCount: 1, SetLastError: 1, SetPriorityClass: 2,
  SetProcessAffinityMask: 2, SetProcessWorkingSetSize: 3, SetStdHandle: 2, SetThreadAffinityMask: 2, SetThreadContext: 2, SetThreadLocale: 1,
  SetThreadPriority: 2, SetUnhandledExceptionFilter: 1, SizeofResource: 2, Sleep: 1, SleepEx: 2, SuspendThread: 1, SystemTimeToFileTime: 2,
  SystemTimeToTzSpecificLocalTime: 3, TerminateProcess: 2, TerminateThread: 2, TlsAlloc: 0, TlsFree: 1, TlsGetValue: 1, TlsSetValue: 2,
  TryEnterCriticalSection: 1, UnhandledExceptionFilter: 1, UnlockFile: 5, UnmapViewOfFile: 1, VirtualAlloc: 4, VirtualFree: 3, VirtualLock: 2,
  VirtualProtect: 4, VirtualQuery: 3, VirtualUnlock: 2, WaitForMultipleObjects: 4, WaitForSingleObject: 2, WaitForSingleObjectEx: 3, WideCharToMultiByte: 8,
  WriteFile: 5, WritePrivateProfileStringA: 4, WriteProcessMemory: 5, lstrcatA: 2, lstrcmpA: 2, lstrcmpiA: 2, lstrcpyA: 2, lstrcpynA: 3, lstrlenA: 1,
  lstrlenW: 1, lstrcpyW: 2, lstrcatW: 2, lstrcmpW: 2, lstrcmpiW: 2,
  // user32
  AdjustWindowRect: 3, AdjustWindowRectEx: 4, AppendMenuA: 4, BeginPaint: 2, BringWindowToTop: 1, CallWindowProcA: 5, CharLowerA: 1, CharNextA: 1,
  CharUpperA: 1, CheckMenuItem: 3, ChildWindowFromPoint: 3, ClientToScreen: 2, ClipCursor: 1, CloseClipboard: 0, CreateCursor: 7, CreateDialogParamA: 5,
  CreateIconIndirect: 1, CreateMenu: 0, CreatePopupMenu: 0, CreateWindowExA: 12, CreateWindowExW: 12, DefWindowProcA: 4, DefWindowProcW: 4, DeferWindowPos: 8,
  DeleteMenu: 3, DestroyCursor: 1, DestroyIcon: 1, DestroyMenu: 1, DestroyWindow: 1, DialogBoxParamA: 5, DispatchMessageA: 1, DispatchMessageW: 1,
  DrawIcon: 4, DrawTextA: 5, EmptyClipboard: 0, EnableMenuItem: 3, EnableWindow: 2, EndDialog: 2, EndPaint: 2, EnumDisplayDevicesA: 4,
  EnumDisplayMonitors: 4, EnumDisplaySettingsA: 3, EnumThreadWindows: 3, EnumWindows: 2, ExitWindowsEx: 2, FillRect: 3, FindWindowA: 2, FlashWindow: 2,
  FrameRect: 3, GetActiveWindow: 0, GetAsyncKeyState: 1, GetCapture: 0, GetCaretBlinkTime: 0, GetClassInfoA: 3, GetClassInfoExA: 3, GetClassLongA: 2,
  GetClassNameA: 3, GetClientRect: 2, GetClipboardData: 1, GetCursor: 0, GetCursorPos: 1, GetDC: 1, GetDCEx: 3, GetDesktopWindow: 0, GetDlgItem: 2,
  GetDlgItemTextA: 4, GetDoubleClickTime: 0, GetFocus: 0, GetForegroundWindow: 0, GetKeyNameTextA: 3, GetKeyState: 1, GetKeyboardLayout: 1,
  GetKeyboardState: 1, GetKeyboardType: 1, GetLastActivePopup: 1, GetMenu: 1, GetMessageA: 4, GetMessageW: 4, GetMessagePos: 0, GetMessageTime: 0,
  GetMonitorInfoA: 2, GetParent: 1, GetProcessWindowStation: 0, GetQueueStatus: 1, GetSubMenu: 2, GetSysColor: 1, GetSysColorBrush: 1,
  GetSystemMenu: 2, GetSystemMetrics: 1, GetTopWindow: 1, GetUpdateRect: 3, GetUserObjectInformationA: 5, GetWindow: 2, GetWindowDC: 1,
  GetWindowLongA: 2, GetWindowLongW: 2, GetWindowPlacement: 2, GetWindowRect: 2, GetWindowTextA: 3, GetWindowTextLengthA: 1, GetWindowThreadProcessId: 2,
  InsertMenuA: 5, IntersectRect: 3, InvalidateRect: 3, InvalidateRgn: 3, IsChild: 2, IsDialogMessageA: 2, IsIconic: 1, IsRectEmpty: 1, IsWindow: 1,
  IsWindowEnabled: 1, IsWindowVisible: 1, IsZoomed: 1, KillTimer: 2, LoadAcceleratorsA: 2, LoadBitmapA: 2, LoadCursorA: 2, LoadCursorW: 2,
  LoadCursorFromFileA: 1, LoadIconA: 2, LoadIconW: 2, LoadImageA: 6, LoadMenuA: 2, LoadStringA: 4, LoadStringW: 4, MapVirtualKeyA: 2, MapWindowPoints: 4,
  MessageBeep: 1, MessageBoxA: 4, MessageBoxW: 4, MoveWindow: 6, MsgWaitForMultipleObjects: 5, OffsetRect: 3, OpenClipboard: 1, PeekMessageA: 5,
  PeekMessageW: 5, PostMessageA: 4, PostMessageW: 4, PostQuitMessage: 1, PostThreadMessageA: 4, PtInRect: 3, RedrawWindow: 4, RegisterClassA: 1,
  RegisterClassW: 1, RegisterClassExA: 1, RegisterClassExW: 1, RegisterClipboardFormatA: 1, RegisterHotKey: 4, RegisterWindowMessageA: 1,
  ReleaseCapture: 0, ReleaseDC: 2, RemoveMenu: 3, ScreenToClient: 2, SendMessageA: 4, SendMessageW: 4, SendMessageTimeoutA: 7, SetActiveWindow: 1,
  SetCapture: 1, SetClassLongA: 3, SetClipboardData: 2, SetCursor: 1, SetCursorPos: 2, SetFocus: 1, SetForegroundWindow: 1, SetMenu: 2, SetParent: 2,
  SetRect: 5, SetRectEmpty: 1, SetTimer: 4, SetWindowLongA: 3, SetWindowLongW: 3, SetWindowPlacement: 2, SetWindowPos: 7, SetWindowTextA: 2,
  SetWindowsHookExA: 4, ShowCursor: 1, ShowWindow: 2, SystemParametersInfoA: 4, TrackPopupMenu: 7, TranslateAcceleratorA: 3, TranslateMessage: 1,
  UnhookWindowsHookEx: 1, UnionRect: 3, UnregisterClassA: 2, UpdateWindow: 1, ValidateRect: 2, WaitMessage: 0, WindowFromPoint: 2, wsprintfA: -1,
  ChangeDisplaySettingsA: 2, ChangeDisplaySettingsExA: 5, GetRawInputData: 5, RegisterRawInputDevices: 3, GetKeyboardLayoutNameA: 1, ToAscii: 5,
  ToUnicode: 6, VkKeyScanA: 1, OemToCharA: 2, CharToOemA: 2, GetMenuItemCount: 1, GetMenuItemInfoA: 4, SetMenuItemInfoA: 4, DrawMenuBar: 1,
  // gdi32
  BitBlt: 9, ChoosePixelFormat: 2, CombineRgn: 4, CreateBitmap: 5, CreateCompatibleBitmap: 3, CreateCompatibleDC: 1, CreateDCA: 4,
  CreateDIBSection: 6, CreateDIBitmap: 6, CreateFontA: 14, CreateFontIndirectA: 1, CreatePalette: 1, CreatePen: 3, CreateRectRgn: 4, CreateSolidBrush: 1,
  DeleteDC: 1, DeleteObject: 1, DescribePixelFormat: 4, Ellipse: 5, ExtTextOutA: 8, GdiFlush: 0, GetBitmapBits: 3, GetClipBox: 2, GetCurrentObject: 2,
  GetDIBits: 7, GetDeviceCaps: 2, GetDeviceGammaRamp: 2, GetObjectA: 3, GetPixel: 3, GetStockObject: 1, GetSystemPaletteEntries: 4, GetTextExtentPoint32A: 4,
  GetTextMetricsA: 2, LineTo: 3, MoveToEx: 4, PatBlt: 6, Polygon: 3, Polyline: 3, RealizePalette: 1, Rectangle: 5, RestoreDC: 2, SaveDC: 1,
  SelectObject: 2, SelectPalette: 3, SetBkColor: 2, SetBkMode: 2, SetDIBits: 7, SetDIBitsToDevice: 12, SetDeviceGammaRamp: 2, SetPixel: 4,
  SetPixelFormat: 3, SetStretchBltMode: 2, SetTextColor: 2, StretchBlt: 11, StretchDIBits: 13, SwapBuffers: 1, TextOutA: 5, GetTextExtentPointA: 4,
  // advapi32
  RegCloseKey: 1, RegCreateKeyA: 3, RegCreateKeyExA: 9, RegDeleteKeyA: 2, RegDeleteValueA: 2, RegEnumKeyExA: 8, RegEnumValueA: 8, RegOpenKeyA: 3,
  RegOpenKeyExA: 5, RegQueryValueA: 4, RegQueryValueExA: 6, RegSetValueExA: 6, RegQueryInfoKeyA: 12, GetUserNameA: 2, CryptAcquireContextA: 5,
  CryptGenRandom: 3, CryptReleaseContext: 2, OpenProcessToken: 3, GetTokenInformation: 5, LookupPrivilegeValueA: 3, AdjustTokenPrivileges: 6,
  RegOpenKeyExW: 5, RegQueryValueExW: 6, RegSetValueExW: 6, RegCreateKeyExW: 9,
  // winmm
  timeGetTime: 0, timeBeginPeriod: 1, timeEndPeriod: 1, timeGetDevCaps: 2, timeSetEvent: 5, timeKillEvent: 1, joyGetNumDevs: 0, joyGetPosEx: 2,
  joyGetDevCapsA: 3, mciSendCommandA: 4, mciSendStringA: 4, waveOutOpen: 6, waveOutClose: 1, waveOutPrepareHeader: 3, waveOutUnprepareHeader: 3,
  waveOutWrite: 3, waveOutReset: 1, waveOutGetPosition: 3, waveOutGetNumDevs: 0, waveOutGetDevCapsA: 3, waveOutSetVolume: 2, waveOutGetVolume: 2,
  waveOutPause: 1, waveOutRestart: 1, midiOutOpen: 5, midiOutClose: 1, PlaySoundA: 3, mixerOpen: 5, mixerClose: 1,
  // ole32 / shell32 / version / imm32
  CoInitialize: 1, CoInitializeEx: 2, CoUninitialize: 0, CoCreateInstance: 5, CoTaskMemAlloc: 1, CoTaskMemFree: 1, CLSIDFromString: 2, StringFromGUID2: 3,
  ShellExecuteA: 6, SHGetFolderPathA: 5, SHGetSpecialFolderPathA: 4, ShellExecuteExA: 1, SHGetFileInfoA: 5, GetFileVersionInfoA: 4,
  GetFileVersionInfoSizeA: 2, VerQueryValueA: 4, ImmAssociateContext: 2, ImmGetContext: 1, ImmReleaseContext: 2, ImmSetCompositionWindow: 2,
  ImmGetCompositionStringA: 4, ImmSetOpenStatus: 2, ImmGetOpenStatus: 1, ImmDisableIME: 1,
  // ws2_32
  WSAStartup: 2, WSACleanup: 0, WSAGetLastError: 0, WSASetLastError: 1, socket: 3, closesocket: 1, bind: 3, connect: 3, listen: 2, accept: 3,
  send: 4, recv: 4, sendto: 6, recvfrom: 6, select: 5, ioctlsocket: 3, setsockopt: 5, getsockopt: 5, gethostbyname: 1, gethostname: 2,
  inet_addr: 1, inet_ntoa: 1, htons: 1, ntohs: 1, htonl: 1, ntohl: 1, getsockname: 3, getpeername: 3, shutdown: 2, WSAAsyncSelect: 4,
  __WSAFDIsSet: 2, WSAEventSelect: 3, WSACreateEvent: 0, WSACloseEvent: 1, WSAWaitForMultipleEvents: 5, WSAEnumNetworkEvents: 3, WSAIoctl: 9,
  // dinput / dsound / d3d entry points
  DirectInput8Create: 5, DirectInputCreateA: 4, DirectSoundCreate: 3, DirectSoundCreate8: 3, DirectSoundEnumerateA: 2, DirectSoundCaptureCreate: 3,
  Direct3DCreate8: 1, Direct3DCreate9: 1, DirectDrawCreate: 3, DirectDrawCreateEx: 4, DirectDrawEnumerateA: 2, DirectDrawEnumerateExA: 3,
  // dbghelp
  SymInitialize: 3, SymCleanup: 1, SymSetOptions: 1, SymGetOptions: 0, StackWalk: 9, SymFunctionTableAccess: 2, SymGetModuleBase: 2, SymGetSymFromAddr: 4,
  SymLoadModule: 6, SymGetLineFromAddr: 4, MiniDumpWriteDump: 7, SymFromAddr: 4, SymGetModuleInfo: 3, SymUnDName: 3,
};
