// Argument counts (32-bit stack slots) for common stdcall Win32 functions, used to keep the
// guest stack balanced when an unimplemented import is called (tracing stubs). Only stdcall
// functions matter here: cdecl callers clean up themselves.
export const SIGNATURES = {
  // kernel32
  AddAtomA: 1, AddAtomW: 1, AreFileApisANSI: 0, Beep: 2, CancelIo: 1, CompareFileTime: 2, CompareStringA: 6, CompareStringW: 6,
  ConnectNamedPipe: 2, ContinueDebugEvent: 3, CopyFileA: 3, CopyFileW: 3, CreateDirectoryA: 2, CreateDirectoryW: 2, CreateEventA: 4, CreateEventW: 4,
  CreateFileA: 7, CreateFileW: 7, CreateFileMappingA: 6, CreateFileMappingW: 6, CreateMutexA: 3, CreateMutexW: 3, CreatePipe: 4,
  CreateProcessA: 10, CreateProcessW: 10, CreateSemaphoreA: 4, CreateSemaphoreW: 4, CreateThread: 6, CreateWaitableTimerA: 3,
  DebugBreak: 0, DeleteCriticalSection: 1, DeleteFileA: 1, DeleteFileW: 1, DeviceIoControl: 8, DisableThreadLibraryCalls: 1,
  DuplicateHandle: 7, EnterCriticalSection: 1, ExitProcess: 1, ExitThread: 1, ExpandEnvironmentStringsA: 3, FatalAppExitA: 2,
  FileTimeToDosDateTime: 3, FileTimeToLocalFileTime: 2, FileTimeToSystemTime: 2, FindClose: 1, FindFirstFileA: 2, FindFirstFileW: 2,
  FindNextFileA: 2, FindNextFileW: 2, FindResourceA: 3, FindResourceW: 3, FindResourceExA: 4, FlushFileBuffers: 1, FlushInstructionCache: 3,
  FormatMessageA: 7, FormatMessageW: 7, FreeEnvironmentStringsA: 1, FreeEnvironmentStringsW: 1, FreeLibrary: 1, FreeResource: 1,
  GetACP: 0, GetCPInfo: 2, GetCommandLineA: 0, GetCommandLineW: 0, GetComputerNameA: 2, GetConsoleCP: 0, GetConsoleMode: 2, GetConsoleOutputCP: 0,
  GetCurrentDirectoryA: 2, GetCurrentDirectoryW: 2, GetCurrentProcess: 0, GetCurrentProcessId: 0, GetCurrentThread: 0, GetCurrentThreadId: 0,
  GetDateFormatA: 6, GetDiskFreeSpaceA: 5, GetDiskFreeSpaceExA: 4, GetDriveTypeA: 1, GetEnvironmentStrings: 0, GetEnvironmentStringsW: 0,
  GetEnvironmentVariableA: 3, GetEnvironmentVariableW: 3, GetExitCodeProcess: 2, GetExitCodeThread: 2, GetFileAttributesA: 1, GetFileAttributesW: 1,
  GetFileAttributesExA: 3, GetFileInformationByHandle: 2, GetFileSize: 2, GetFileSizeEx: 2, GetFileTime: 4, GetFileType: 1, GetFullPathNameA: 4, GetFullPathNameW: 4,
  GetLastError: 0, GetLocalTime: 1, GetLocaleInfoA: 4, GetLocaleInfoW: 4, GetLogicalDrives: 0, GetLogicalDriveStringsA: 2, GetLongPathNameA: 3,
  GetModuleFileNameA: 3, GetModuleFileNameW: 3, GetModuleHandleA: 1, GetModuleHandleW: 1, GetModuleHandleExA: 3, GetOEMCP: 0, GetOverlappedResult: 4,
  GetPriorityClass: 1, GetPrivateProfileIntA: 4, GetPrivateProfileStringA: 6, GetProcAddress: 2, GetProcessAffinityMask: 3, GetProcessHeap: 0,
  GetProcessTimes: 5, GetProcessVersion: 1, GetProcessWorkingSetSize: 3, GetShortPathNameA: 3, GetStartupInfoA: 1, GetStartupInfoW: 1, GetStdHandle: 1,
  GetStringTypeA: 5, GetStringTypeW: 4, GetStringTypeExA: 5, GetSystemDefaultLCID: 0, GetSystemDefaultLangID: 0, GetSystemDirectoryA: 2, GetSystemDirectoryW: 2,
  GetSystemInfo: 1, GetSystemTime: 1, GetSystemTimeAsFileTime: 1, GetTempFileNameA: 4, GetTempPathA: 2, GetTempPathW: 2, GetThreadContext: 2, GetThreadLocale: 0,
  GetThreadPriority: 1, GetThreadTimes: 5, GetTickCount: 0, GetTimeFormatA: 6, GetTimeZoneInformation: 1, GetUserDefaultLCID: 0, GetUserDefaultLangID: 0,
  GetVersion: 0, GetVersionExA: 1, GetVersionExW: 1, GetVolumeInformationA: 8, GetWindowsDirectoryA: 2, GetWindowsDirectoryW: 2, GlobalAlloc: 2, GlobalFlags: 1,
  GlobalFree: 1, GlobalHandle: 1, GlobalLock: 1, GlobalMemoryStatus: 1, GlobalMemoryStatusEx: 1, GlobalReAlloc: 3, GlobalSize: 1, GlobalUnlock: 1,
  HeapAlloc: 3, HeapCompact: 2, HeapCreate: 3, HeapDestroy: 1, HeapFree: 3, HeapReAlloc: 4, HeapSize: 3, HeapValidate: 3, HeapWalk: 2,
  InitializeCriticalSection: 1, InitializeCriticalSectionAndSpinCount: 2, InterlockedCompareExchange: 3, InterlockedDecrement: 1, InterlockedExchange: 2,
  InterlockedExchangeAdd: 2, InterlockedIncrement: 1, IsBadCodePtr: 1, IsBadReadPtr: 2, IsBadStringPtrA: 2, IsBadWritePtr: 2, IsDBCSLeadByte: 1,
  IsDBCSLeadByteEx: 2, IsDebuggerPresent: 0, IsProcessorFeaturePresent: 1, IsValidCodePage: 1, IsValidLocale: 2, LCMapStringA: 6, LCMapStringW: 6,
  LeaveCriticalSection: 1, LoadLibraryA: 1, LoadLibraryW: 1, LoadLibraryExA: 3, LoadLibraryExW: 3, LoadResource: 2, LocalAlloc: 2, LocalFileTimeToFileTime: 2,
  LocalFree: 1, LocalLock: 1, LocalReAlloc: 3, LocalSize: 1, LocalUnlock: 1, LockFile: 5, LockResource: 1, MapViewOfFile: 5, MoveFileA: 2, MoveFileExA: 3,
  MulDiv: 3, MultiByteToWideChar: 6, OpenEventA: 3, OpenFile: 3, OpenMutexA: 3, OpenProcess: 3, OutputDebugStringA: 1, OutputDebugStringW: 1,
  PeekNamedPipe: 6, PulseEvent: 1, QueryPerformanceCounter: 1, QueryPerformanceFrequency: 1, RaiseException: 4, ReadFile: 5, ReadProcessMemory: 5,
  ReleaseMutex: 1, ReleaseSemaphore: 3, RemoveDirectoryA: 1, ResetEvent: 1, ResumeThread: 1, RtlUnwind: 4, SearchPathA: 6, SetConsoleCtrlHandler: 2,
  SetCurrentDirectoryA: 1, SetCurrentDirectoryW: 1, SetEndOfFile: 1, SetEnvironmentVariableA: 2, SetEnvironmentVariableW: 2, SetErrorMode: 1, SetEvent: 1,
  SetFileAttributesA: 2, SetFilePointer: 4, SetFilePointerEx: 5, SetFileTime: 4, SetHandleCount: 1, SetLastError: 1, SetPriorityClass: 2,
  SetProcessAffinityMask: 2, SetProcessWorkingSetSize: 3, SetStdHandle: 2, SetThreadAffinityMask: 2, SetThreadContext: 2, SetThreadLocale: 1,
  SetThreadPriority: 2, SetUnhandledExceptionFilter: 1, SizeofResource: 2, Sleep: 1, SleepEx: 2, SuspendThread: 1, SystemTimeToFileTime: 2,
  SystemTimeToTzSpecificLocalTime: 3, TerminateProcess: 2, TerminateThread: 2, TlsAlloc: 0, TlsFree: 1, TlsGetValue: 1, TlsSetValue: 2,
  TryEnterCriticalSection: 1, UnhandledExceptionFilter: 1, UnlockFile: 5, UnmapViewOfFile: 1, VirtualAlloc: 4, VirtualFree: 3, VirtualLock: 2,
  VirtualProtect: 4, VirtualQuery: 3, VirtualUnlock: 2, WaitForMultipleObjects: 4, WaitForSingleObject: 2, WaitForSingleObjectEx: 3, WideCharToMultiByte: 8,
  WriteFile: 5, WritePrivateProfileStringA: 4, WriteProcessMemory: 5, lstrcatA: 2, lstrcmpA: 2, lstrcmpiA: 2, lstrcpyA: 2, lstrcpynA: 3, lstrlenA: 1,
  lstrlenW: 1, lstrcpyW: 2, lstrcatW: 2, lstrcmpW: 2, lstrcmpiW: 2,
  CreateToolhelp32Snapshot: 2, Module32First: 2, Module32Next: 2, Module32FirstW: 2, Module32NextW: 2, Process32First: 2, Process32Next: 2, Process32FirstW: 2, Process32NextW: 2,
  Thread32First: 2, Thread32Next: 2, Heap32ListFirst: 2, Heap32ListNext: 2, Heap32First: 3, Heap32Next: 1, Toolhelp32ReadProcessMemory: 5,
  FlsAlloc: 1, FlsFree: 1, FlsGetValue: 1, FlsSetValue: 2, GetDateFormatW: 6, GetTimeFormatW: 6, GetStringTypeExW: 5, lstrcmpi: 2, lstrcpy: 2, lstrcpyn: 3, lstrcmp: 2, lstrcat: 2, lstrlen: 1,
  SetCommState: 2, GetCommState: 2, SetupComm: 3, PurgeComm: 2, SetCommTimeouts: 2, GetCommTimeouts: 2, SetCommMask: 2, GetCommMask: 2, WaitCommEvent: 3, GetCommConfig: 3, SetCommConfig: 3, ClearCommError: 3, EscapeCommFunction: 2, TransmitCommChar: 2, GetCommModemStatus: 2,
  ReadConsoleInputA: 4, GetNumberOfConsoleInputEvents: 2, SetConsoleCursorInfo: 2, SetConsoleScreenBufferSize: 2, SetConsoleWindowInfo: 3, WriteConsoleOutputA: 5, SetNamedPipeHandleState: 4, PeekConsoleInputA: 4, FillConsoleOutputCharacterA: 5, FillConsoleOutputAttribute: 5, SetConsoleCursorPosition: 2, GetConsoleCursorInfo: 2, ReadConsoleOutputA: 5, WriteConsoleOutputCharacterA: 5, GetLargestConsoleWindowSize: 1, ScrollConsoleScreenBufferA: 5,
  IsWindowUnicode: 1, GetCharABCWidthsI: 5, GetGlyphIndicesW: 5, GetTextExtentPointI: 4, SetDIBColorTable: 4, GetDIBColorTable: 4,
  // gdiplus flat API (GpStatus returns)
  GdiplusStartup: 3, GdiplusShutdown: 1, GdipAlloc: 1, GdipFree: 1, GdipCreateBitmapFromFile: 2, GdipCreateBitmapFromFileICM: 2, GdipCreateBitmapFromStream: 2, GdipCreateBitmapFromStreamICM: 2,
  GdipCreateBitmapFromScan0: 6, GdipCreateBitmapFromHBITMAP: 3, GdipCreateBitmapFromResource: 3, GdipCreateBitmapFromGraphics: 4, GdipCreateBitmapFromHICON: 2, GdipCreateHBITMAPFromBitmap: 3, GdipCreateHICONFromBitmap: 2,
  GdipDisposeImage: 1, GdipGetImageWidth: 2, GdipGetImageHeight: 2, GdipGetImagePixelFormat: 2, GdipGetImageGraphicsContext: 2, GdipBitmapLockBits: 5, GdipBitmapUnlockBits: 2, GdipBitmapGetPixel: 4, GdipBitmapSetPixel: 4,
  GdipLoadImageFromFile: 2, GdipLoadImageFromFileICM: 2, GdipLoadImageFromStream: 2, GdipLoadImageFromStreamICM: 2, GdipSaveImageToFile: 4, GdipSaveImageToStream: 4, GdipGetImageEncodersSize: 2, GdipGetImageEncoders: 3, GdipGetImageDecodersSize: 2, GdipGetImageDecoders: 3,
  GdipCreateFromHDC: 2, GdipCreateFromHDC2: 3, GdipCreateFromHWND: 2, GdipDeleteGraphics: 1, GdipDrawImage: 4, GdipDrawImageI: 4, GdipDrawImageRect: 6, GdipDrawImageRectI: 6, GdipDrawImageRectRect: 11, GdipDrawImageRectRectI: 11,
  GdipDrawImagePointRect: 9, GdipDrawImagePointRectI: 9, GdipDrawImagePointsRect: 11, GdipDrawImagePointsRectI: 11, GdipGraphicsClear: 2, GdipSetInterpolationMode: 2, GdipGetInterpolationMode: 2, GdipSetSmoothingMode: 2, GdipGetSmoothingMode: 2,
  GdipSetCompositingMode: 2, GdipSetCompositingQuality: 2, GdipSetPixelOffsetMode: 2, GdipGetPixelOffsetMode: 2, GdipSetTextRenderingHint: 2, GdipSetTextContrast: 2, GdipCreateSolidFill: 2, GdipSetSolidFillColor: 2, GdipDeleteBrush: 1,
  GdipCreatePen1: 4, GdipCreatePen2: 4, GdipDeletePen: 1, GdipSetPenWidth: 2, GdipSetPenColor: 2, GdipFillRectangle: 6, GdipFillRectangleI: 6, GdipDrawRectangle: 6, GdipDrawRectangleI: 6, GdipDrawLine: 6, GdipDrawLineI: 6, GdipFillEllipse: 6, GdipFillEllipseI: 6, GdipDrawEllipse: 6, GdipDrawEllipseI: 6,
  GdipCreateFont: 5, GdipCreateFontFromDC: 2, GdipCreateFontFromLogfontA: 3, GdipCreateFontFromLogfontW: 3, GdipCreateFontFamilyFromName: 3, GdipGetGenericFontFamilySansSerif: 1, GdipDeleteFont: 1, GdipDeleteFontFamily: 1, GdipGetFontHeight: 3, GdipGetFontSize: 2,
  GdipDrawString: 7, GdipMeasureString: 8, GdipCreateStringFormat: 3, GdipStringFormatGetGenericDefault: 1, GdipStringFormatGetGenericTypographic: 1, GdipDeleteStringFormat: 1, GdipSetStringFormatAlign: 2, GdipSetStringFormatLineAlign: 2, GdipSetStringFormatFlags: 2, GdipSetStringFormatTrimming: 2,
  GdipGetImageDimension: 3, GdipGetImageBounds: 3, GdipImageGetFrameCount: 3, GdipImageGetFrameDimensionsCount: 2, GdipImageGetFrameDimensionsList: 3, GdipImageSelectActiveFrame: 3, GdipCloneImage: 2, GdipCloneBitmapArea: 7, GdipCloneBitmapAreaI: 7, GdipGetImageThumbnail: 6, GdipGetImageFlags: 2, GdipGetImageRawFormat: 2, GdipGetImageType: 2,
  GdipGetPropertyItemSize: 3, GdipGetPropertyItem: 4, GdipGetPropertyCount: 2, GdipGetPropertyIdList: 3, GdipImageRotateFlip: 2, GdipGetImagePalette: 3, GdipSetImagePalette: 2, GdipGetImagePaletteSize: 2, GdipGetImageHorizontalResolution: 2, GdipGetImageVerticalResolution: 2, GdipBitmapSetResolution: 3,
  GdipCreateImageAttributes: 1, GdipDisposeImageAttributes: 1, GdipSetImageAttributesColorKeys: 5, GdipSetImageAttributesColorMatrix: 6, GdipSetImageAttributesWrapMode: 4, GdipCreateTexture: 3, GdipCreateTextureIA: 7, GdipGetDC: 2, GdipReleaseDC: 2, GdipSetPageUnit: 2, GdipSetPageScale: 2,
  GdipSetWorldTransform: 2, GdipGetWorldTransform: 2, GdipResetWorldTransform: 1, GdipTranslateWorldTransform: 4, GdipScaleWorldTransform: 4, GdipRotateWorldTransform: 3, GdipCreateMatrix: 1, GdipCreateMatrix2: 7, GdipDeleteMatrix: 1, GdipSetMatrixElements: 7, GdipTranslateMatrix: 4, GdipScaleMatrix: 4,
  GdipSetClipRect: 6, GdipSetClipRectI: 6, GdipSetClipRegion: 3, GdipSetClipPath: 3, GdipResetClip: 1, GdipGetClipBounds: 2, GdipGetVisibleClipBounds: 2, GdipCreatePath: 2, GdipDeletePath: 1, GdipResetPath: 1, GdipAddPathLine: 5, GdipAddPathLineI: 5, GdipAddPathArc: 7, GdipAddPathArcI: 7, GdipAddPathRectangle: 5, GdipAddPathRectangleI: 5,
  GdipAddPathEllipse: 5, GdipAddPathString: 7, GdipClosePathFigure: 1, GdipStartPathFigure: 1, GdipFillPath: 3, GdipDrawPath: 3, GdipCreateRegion: 1, GdipCreateRegionRect: 2, GdipCreateRegionRectI: 2, GdipCreateRegionPath: 2, GdipDeleteRegion: 1, GdipCombineRegionRect: 3, GdipCombineRegionRectI: 3,
  GdipCreateLineBrush: 6, GdipCreateLineBrushI: 6, GdipCreateLineBrushFromRect: 6, GdipCreateLineBrushFromRectI: 6, GdipCreateHatchBrush: 4, GdipCreatePathGradient: 4, GdipCreatePathGradientI: 4, GdipCreatePathGradientFromPath: 2, GdipSetPathGradientCenterColor: 2, GdipSetPathGradientSurroundColorsWithCount: 3,
  GdipFillPolygon: 5, GdipFillPolygonI: 5, GdipFillPolygon2: 4, GdipFillPolygon2I: 4, GdipDrawPolygon: 4, GdipDrawPolygonI: 4, GdipDrawLines: 4, GdipDrawLinesI: 4, GdipDrawArc: 8, GdipDrawArcI: 8, GdipDrawBezier: 10, GdipDrawBezierI: 10, GdipDrawCurve: 4, GdipDrawCurveI: 4,
  GdipFillPie: 8, GdipFillPieI: 8, GdipDrawPie: 8, GdipDrawPieI: 8, GdipDrawCachedBitmap: 4, GdipCreateCachedBitmap: 3, GdipDeleteCachedBitmap: 1, GdipCreateHalftonePalette: 0, GdipSetPenDashStyle: 2, GdipSetPenLineJoin: 2, GdipSetPenStartCap: 2, GdipSetPenEndCap: 2, GdipSetPenMode: 2, GdipSetPenBrushFill: 2,
  GdipCloneBrush: 2, GdipClonePen: 2, GdipCloneFont: 2, GdipCloneStringFormat: 2, GdipClonePath: 2, GdipCloneRegion: 2, GdipCloneMatrix: 2, GdipCloneImageAttributes: 2, GdipGetRegionBounds: 3, GdipGetRegionBoundsI: 3, GdipIsVisiblePoint: 4, GdipIsVisiblePointI: 4, GdipIsVisibleRegionPoint: 5, GdipIsVisibleRegionPointI: 5,
  GdipGetFamilyName: 3, GdipGetFontStyle: 2, GdipGetFontUnit: 2, GdipGetLogFontA: 3, GdipGetLogFontW: 3, GdipNewInstalledFontCollection: 1, GdipNewPrivateFontCollection: 1, GdipDeletePrivateFontCollection: 1, GdipPrivateAddFontFile: 2, GdipGetFontCollectionFamilyCount: 2, GdipGetFontCollectionFamilyList: 4,
  GdipSetRenderingOrigin: 3, GdipBeginContainer: 5, GdipBeginContainerI: 5, GdipBeginContainer2: 2, GdipEndContainer: 2, GdipSaveGraphics: 2, GdipRestoreGraphics: 2, GdipFlush: 2, GdipGetDpiX: 2, GdipGetDpiY: 2, GdipGetPageUnit: 2, GdipGetPageScale: 2, GdipGetNearestColor: 2, GdipSetPropertyItem: 2, GdipRemovePropertyItem: 2,
  GdipCreateMetafileFromFile: 2, GdipCreateMetafileFromWmf: 3, GdipCreateMetafileFromEmf: 3, GdipRecordMetafile: 6, GdipDeleteEffect: 1, GdipBitmapConvertFormat: 6, GdipInitializePalette: 5, GdipBitmapApplyEffect: 5, GdipImageForceValidation: 1, GdipTestControl: 2, GdipGetImageItemData: 2, GdipTransformPoints: 5, GdipTransformPointsI: 5,
  // user32
  AdjustWindowRect: 3, AdjustWindowRectEx: 4, AppendMenuA: 4, BeginPaint: 2, BringWindowToTop: 1, CallWindowProcA: 5, CharLowerA: 1, CharNextA: 1,
  CharUpperA: 1, CheckMenuItem: 3, ChildWindowFromPoint: 3, ClientToScreen: 2, ClipCursor: 1, CloseClipboard: 0, CreateCursor: 7, CreateDialogParamA: 5,
  CreateIconIndirect: 1, CreateMenu: 0, CreatePopupMenu: 0, CreateWindowExA: 12, CreateWindowExW: 12, DefWindowProcA: 4, DefWindowProcW: 4, DeferWindowPos: 8,
  DeleteMenu: 3, DestroyCursor: 1, DestroyIcon: 1, DestroyMenu: 1, DestroyWindow: 1, DialogBoxParamA: 5, DispatchMessageA: 1, DispatchMessageW: 1,
  DrawIcon: 4, DrawTextA: 5, EmptyClipboard: 0, EnableMenuItem: 3, EnableWindow: 2, EndDialog: 2, EndPaint: 2, EnumDisplayDevicesA: 4,
  EnumDisplayMonitors: 4, EnumDisplaySettingsA: 3, EnumThreadWindows: 3, EnumWindows: 2, ExitWindowsEx: 2, FillRect: 3, FindWindowA: 2, FlashWindow: 2,
  FrameRect: 3, GetActiveWindow: 0, GetAsyncKeyState: 1, GetCapture: 0, GetCaretBlinkTime: 0, GetClassInfoA: 3, GetClassInfoExA: 3, GetClassLongA: 2,
  GetClassNameA: 3, GetClientRect: 2, GetClipboardData: 1, GetCursor: 0, GetCursorPos: 1, GetDC: 1, GetDCEx: 3, GetDesktopWindow: 0, GetDlgItem: 2,
  GetDlgItemTextA: 4, GetDoubleClickTime: 0, GetFocus: 0, GetForegroundWindow: 0, GetKeyNameTextA: 3, GetKeyState: 1, GetKeyboardLayout: 1,
  GetKeyboardState: 1, GetKeyboardType: 1, GetLastActivePopup: 1, GetMenu: 1, GetMessageA: 4, GetMessageW: 4, GetMessagePos: 0, GetMessageTime: 0,
  GetMonitorInfoA: 2, GetParent: 1, GetProcessWindowStation: 0, GetQueueStatus: 1, GetSubMenu: 2, GetSysColor: 1, GetSysColorBrush: 1,
  GetSystemMenu: 2, GetSystemMetrics: 1, GetTopWindow: 1, GetUpdateRect: 3, GetUserObjectInformationA: 5, GetWindow: 2, GetWindowDC: 1,
  GetWindowLongA: 2, GetWindowLongW: 2, GetWindowPlacement: 2, GetWindowRect: 2, GetWindowTextA: 3, GetWindowTextLengthA: 1, GetWindowThreadProcessId: 2,
  InsertMenuA: 5, IntersectRect: 3, InvalidateRect: 3, InvalidateRgn: 3, IsChild: 2, IsDialogMessageA: 2, IsIconic: 1, IsRectEmpty: 1, IsWindow: 1,
  IsWindowEnabled: 1, IsWindowVisible: 1, IsZoomed: 1, KillTimer: 2, LoadAcceleratorsA: 2, LoadBitmapA: 2, LoadCursorA: 2, LoadCursorW: 2,
  LoadCursorFromFileA: 1, LoadIconA: 2, LoadIconW: 2, LoadImageA: 6, LoadMenuA: 2, LoadStringA: 4, LoadStringW: 4, MapVirtualKeyA: 2, MapWindowPoints: 4,
  MessageBeep: 1, MessageBoxA: 4, MessageBoxW: 4, MoveWindow: 6, MsgWaitForMultipleObjects: 5, OffsetRect: 3, OpenClipboard: 1, PeekMessageA: 5,
  PeekMessageW: 5, PostMessageA: 4, PostMessageW: 4, PostQuitMessage: 1, PostThreadMessageA: 4, PtInRect: 3, RedrawWindow: 4, RegisterClassA: 1,
  RegisterClassW: 1, RegisterClassExA: 1, RegisterClassExW: 1, RegisterClipboardFormatA: 1, RegisterHotKey: 4, RegisterWindowMessageA: 1,
  ReleaseCapture: 0, ReleaseDC: 2, RemoveMenu: 3, ScreenToClient: 2, SendMessageA: 4, SendMessageW: 4, SendMessageTimeoutA: 7, SetActiveWindow: 1,
  SetCapture: 1, SetClassLongA: 3, SetClipboardData: 2, SetCursor: 1, SetCursorPos: 2, SetFocus: 1, SetForegroundWindow: 1, SetMenu: 2, SetParent: 2,
  SetRect: 5, SetRectEmpty: 1, SetTimer: 4, SetWindowLongA: 3, SetWindowLongW: 3, SetWindowPlacement: 2, SetWindowPos: 7, SetWindowTextA: 2,
  SetWindowsHookExA: 4, ShowCursor: 1, ShowWindow: 2, SystemParametersInfoA: 4, TrackPopupMenu: 7, TranslateAcceleratorA: 3, TranslateMessage: 1,
  UnhookWindowsHookEx: 1, UnionRect: 3, UnregisterClassA: 2, UpdateWindow: 1, ValidateRect: 2, WaitMessage: 0, WindowFromPoint: 2, wsprintfA: -1,
  ChangeDisplaySettingsA: 2, ChangeDisplaySettingsExA: 5, GetRawInputData: 5, RegisterRawInputDevices: 3, GetKeyboardLayoutNameA: 1, ToAscii: 5,
  ToUnicode: 6, VkKeyScanA: 1, OemToCharA: 2, CharToOemA: 2, GetMenuItemCount: 1, GetMenuItemInfoA: 4, SetMenuItemInfoA: 4, DrawMenuBar: 1,
  // gdi32
  BitBlt: 9, ChoosePixelFormat: 2, CombineRgn: 4, CreateBitmap: 5, CreateCompatibleBitmap: 3, CreateCompatibleDC: 1, CreateDCA: 4,
  CreateDIBSection: 6, CreateDIBitmap: 6, CreateFontA: 14, CreateFontIndirectA: 1, CreatePalette: 1, CreatePen: 3, CreateRectRgn: 4, CreateSolidBrush: 1,
  DeleteDC: 1, DeleteObject: 1, DescribePixelFormat: 4, Ellipse: 5, ExtTextOutA: 8, GdiFlush: 0, GetBitmapBits: 3, GetClipBox: 2, GetCurrentObject: 2,
  GetDIBits: 7, GetDeviceCaps: 2, GetDeviceGammaRamp: 2, GetObjectA: 3, GetPixel: 3, GetStockObject: 1, GetSystemPaletteEntries: 4, GetTextExtentPoint32A: 4,
  GetTextMetricsA: 2, LineTo: 3, MoveToEx: 4, PatBlt: 6, Polygon: 3, Polyline: 3, RealizePalette: 1, Rectangle: 5, RestoreDC: 2, SaveDC: 1,
  SelectObject: 2, SelectPalette: 3, SetBkColor: 2, SetBkMode: 2, SetDIBits: 7, SetDIBitsToDevice: 12, SetDeviceGammaRamp: 2, SetPixel: 4,
  SetPixelFormat: 3, SetStretchBltMode: 2, SetTextColor: 2, StretchBlt: 11, StretchDIBits: 13, SwapBuffers: 1, TextOutA: 5, GetTextExtentPointA: 4,
  // advapi32
  RegCloseKey: 1, RegCreateKeyA: 3, RegCreateKeyExA: 9, RegDeleteKeyA: 2, RegDeleteValueA: 2, RegEnumKeyExA: 8, RegEnumValueA: 8, RegOpenKeyA: 3,
  RegOpenKeyExA: 5, RegQueryValueA: 4, RegQueryValueExA: 6, RegSetValueExA: 6, RegQueryInfoKeyA: 12, GetUserNameA: 2, CryptAcquireContextA: 5,
  CryptGenRandom: 3, CryptReleaseContext: 2, OpenProcessToken: 3, GetTokenInformation: 5, LookupPrivilegeValueA: 3, AdjustTokenPrivileges: 6,
  RegOpenKeyExW: 5, RegQueryValueExW: 6, RegSetValueExW: 6, RegCreateKeyExW: 9,
  // winmm
  timeGetTime: 0, timeBeginPeriod: 1, timeEndPeriod: 1, timeGetDevCaps: 2, timeSetEvent: 5, timeKillEvent: 1, joyGetNumDevs: 0, joyGetPosEx: 2,
  joyGetDevCapsA: 3, mciSendCommandA: 4, mciSendStringA: 4, waveOutOpen: 6, waveOutClose: 1, waveOutPrepareHeader: 3, waveOutUnprepareHeader: 3,
  waveOutWrite: 3, waveOutReset: 1, waveOutGetPosition: 3, waveOutGetNumDevs: 0, waveOutGetDevCapsA: 3, waveOutSetVolume: 2, waveOutGetVolume: 2,
  waveOutPause: 1, waveOutRestart: 1, midiOutOpen: 5, midiOutClose: 1, PlaySoundA: 3, mixerOpen: 5, mixerClose: 1,
  // ole32 / shell32 / version / imm32
  CoInitialize: 1, CoInitializeEx: 2, CoUninitialize: 0, CoCreateInstance: 5, CoTaskMemAlloc: 1, CoTaskMemFree: 1, CLSIDFromString: 2, StringFromGUID2: 3,
  ShellExecuteA: 6, SHGetFolderPathA: 5, SHGetSpecialFolderPathA: 4, ShellExecuteExA: 1, SHGetFileInfoA: 5, GetFileVersionInfoA: 4,
  GetFileVersionInfoSizeA: 2, VerQueryValueA: 4, ImmAssociateContext: 2, ImmGetContext: 1, ImmReleaseContext: 2, ImmSetCompositionWindow: 2,
  ImmGetCompositionStringA: 4, ImmSetOpenStatus: 2, ImmGetOpenStatus: 1, ImmDisableIME: 1,
  // ws2_32
  WSAStartup: 2, WSACleanup: 0, WSAGetLastError: 0, WSASetLastError: 1, socket: 3, closesocket: 1, bind: 3, connect: 3, listen: 2, accept: 3,
  send: 4, recv: 4, sendto: 6, recvfrom: 6, select: 5, ioctlsocket: 3, setsockopt: 5, getsockopt: 5, gethostbyname: 1, gethostname: 2,
  inet_addr: 1, inet_ntoa: 1, htons: 1, ntohs: 1, htonl: 1, ntohl: 1, getsockname: 3, getpeername: 3, shutdown: 2, WSAAsyncSelect: 4,
  __WSAFDIsSet: 2, WSAEventSelect: 3, WSACreateEvent: 0, WSACloseEvent: 1, WSAWaitForMultipleEvents: 5, WSAEnumNetworkEvents: 3, WSAIoctl: 9,
  // dinput / dsound / d3d entry points
  DirectInput8Create: 5, DirectInputCreateA: 4, DirectSoundCreate: 3, DirectSoundCreate8: 3, DirectSoundEnumerateA: 2, DirectSoundCaptureCreate: 3,
  Direct3DCreate8: 1, Direct3DCreate9: 1, DirectDrawCreate: 3, DirectDrawCreateEx: 4, DirectDrawEnumerateA: 2, DirectDrawEnumerateExA: 3,
  // dbghelp
  SymInitialize: 3, SymCleanup: 1, SymSetOptions: 1, SymGetOptions: 0, StackWalk: 9, SymFunctionTableAccess: 2, SymGetModuleBase: 2, SymGetSymFromAddr: 4,
  SymLoadModule: 6, SymGetLineFromAddr: 4, MiniDumpWriteDump: 7, SymFromAddr: 4, SymGetModuleInfo: 3, SymUnDName: 3,
};
