// Minimal Win32 declarations for CRT-free test programs (no Windows SDK involved).
#pragma once
#define WINAPI __stdcall
#define DLLIMPORT __declspec(dllimport)
typedef unsigned long DWORD; typedef unsigned short WORD; typedef unsigned char BYTE;
typedef void* HANDLE; typedef int BOOL; typedef long LONG; typedef unsigned int UINT;
typedef HANDLE HWND; typedef HANDLE HDC; typedef HANDLE HINSTANCE; typedef HANDLE HBRUSH; typedef HANDLE HGDIOBJ;
typedef HANDLE HICON; typedef HANDLE HCURSOR; typedef HANDLE HMENU; typedef HANDLE HBITMAP;
typedef UINT WPARAM; typedef LONG LPARAM; typedef LONG LRESULT; typedef DWORD COLORREF;
typedef LRESULT (WINAPI *WNDPROC)(HWND, UINT, WPARAM, LPARAM);
typedef struct { LONG left, top, right, bottom; } RECT;
typedef struct { LONG x, y; } POINT;
typedef struct { HWND hwnd; UINT message; WPARAM wParam; LPARAM lParam; DWORD time; POINT pt; } MSG;
typedef struct { UINT style; WNDPROC lpfnWndProc; int cbClsExtra; int cbWndExtra; HINSTANCE hInstance; HICON hIcon; HCURSOR hCursor; HBRUSH hbrBackground; const char* lpszMenuName; const char* lpszClassName; } WNDCLASSA;
typedef struct { HDC hdc; BOOL fErase; RECT rcPaint; BOOL fRestore; BOOL fIncUpdate; BYTE rgbReserved[32]; } PAINTSTRUCT;
typedef struct { DWORD biSize; LONG biWidth; LONG biHeight; WORD biPlanes; WORD biBitCount; DWORD biCompression; DWORD biSizeImage; LONG biXPelsPerMeter; LONG biYPelsPerMeter; DWORD biClrUsed; DWORD biClrImportant; } BITMAPINFOHEADER;
typedef struct { BITMAPINFOHEADER bmiHeader; DWORD bmiColors[1]; } BITMAPINFO;

DLLIMPORT HANDLE WINAPI GetStdHandle(DWORD);
DLLIMPORT BOOL WINAPI WriteFile(HANDLE, const void*, DWORD, DWORD*, void*);
DLLIMPORT BOOL WINAPI ReadFile(HANDLE, void*, DWORD, DWORD*, void*);
DLLIMPORT void WINAPI ExitProcess(UINT);
DLLIMPORT DWORD WINAPI GetLastError(void);
DLLIMPORT void WINAPI SetLastError(DWORD);
DLLIMPORT HANDLE WINAPI GetModuleHandleA(const char*);
DLLIMPORT void* WINAPI GetProcAddress(HANDLE, const char*);
DLLIMPORT char* WINAPI GetCommandLineA(void);
DLLIMPORT DWORD WINAPI GetTickCount(void);
DLLIMPORT void WINAPI Sleep(DWORD);
DLLIMPORT void* WINAPI HeapAlloc(HANDLE, DWORD, DWORD);
DLLIMPORT BOOL WINAPI HeapFree(HANDLE, DWORD, void*);
DLLIMPORT void* WINAPI HeapReAlloc(HANDLE, DWORD, void*, DWORD);
DLLIMPORT HANDLE WINAPI GetProcessHeap(void);
DLLIMPORT void* WINAPI VirtualAlloc(void*, DWORD, DWORD, DWORD);
DLLIMPORT BOOL WINAPI VirtualFree(void*, DWORD, DWORD);
DLLIMPORT HANDLE WINAPI CreateFileA(const char*, DWORD, DWORD, void*, DWORD, DWORD, HANDLE);
DLLIMPORT BOOL WINAPI CloseHandle(HANDLE);
DLLIMPORT DWORD WINAPI SetFilePointer(HANDLE, LONG, LONG*, DWORD);
DLLIMPORT DWORD WINAPI GetFileSize(HANDLE, DWORD*);
DLLIMPORT DWORD WINAPI TlsAlloc(void);
DLLIMPORT void* WINAPI TlsGetValue(DWORD);
DLLIMPORT BOOL WINAPI TlsSetValue(DWORD, void*);
DLLIMPORT HANDLE WINAPI CreateThread(void*, DWORD, DWORD (WINAPI*)(void*), void*, DWORD, DWORD*);
DLLIMPORT DWORD WINAPI WaitForSingleObject(HANDLE, DWORD);
DLLIMPORT HANDLE WINAPI CreateEventA(void*, BOOL, BOOL, const char*);
DLLIMPORT BOOL WINAPI SetEvent(HANDLE);
DLLIMPORT BOOL WINAPI ResetEvent(HANDLE);
DLLIMPORT HANDLE WINAPI CreateMutexA(void*, BOOL, const char*);
DLLIMPORT BOOL WINAPI ReleaseMutex(HANDLE);
DLLIMPORT HANDLE WINAPI CreateSemaphoreA(void*, LONG, LONG, const char*);
DLLIMPORT BOOL WINAPI ReleaseSemaphore(HANDLE, LONG, LONG*);
DLLIMPORT void WINAPI InitializeCriticalSection(void*);
DLLIMPORT void WINAPI EnterCriticalSection(void*);
DLLIMPORT void WINAPI LeaveCriticalSection(void*);
DLLIMPORT void WINAPI DeleteCriticalSection(void*);
DLLIMPORT LONG WINAPI InterlockedIncrement(LONG*);
DLLIMPORT LONG WINAPI InterlockedDecrement(LONG*);
DLLIMPORT DWORD WINAPI GetCurrentThreadId(void);
DLLIMPORT DWORD WINAPI GetModuleFileNameA(HANDLE, char*, DWORD);
DLLIMPORT HANDLE WINAPI LoadLibraryA(const char*);
DLLIMPORT DWORD WINAPI GetVersion(void);
DLLIMPORT void WINAPI OutputDebugStringA(const char*);
DLLIMPORT int WINAPI lstrlenA(const char*);

// user32
DLLIMPORT WORD WINAPI RegisterClassA(const WNDCLASSA*);
DLLIMPORT HWND WINAPI CreateWindowExA(DWORD, const char*, const char*, DWORD, int, int, int, int, HWND, HMENU, HINSTANCE, void*);
DLLIMPORT LRESULT WINAPI DefWindowProcA(HWND, UINT, WPARAM, LPARAM);
DLLIMPORT BOOL WINAPI ShowWindow(HWND, int);
DLLIMPORT BOOL WINAPI UpdateWindow(HWND);
DLLIMPORT BOOL WINAPI GetMessageA(MSG*, HWND, UINT, UINT);
DLLIMPORT BOOL WINAPI PeekMessageA(MSG*, HWND, UINT, UINT, UINT);
DLLIMPORT BOOL WINAPI TranslateMessage(const MSG*);
DLLIMPORT LRESULT WINAPI DispatchMessageA(const MSG*);
DLLIMPORT void WINAPI PostQuitMessage(int);
DLLIMPORT BOOL WINAPI PostMessageA(HWND, UINT, WPARAM, LPARAM);
DLLIMPORT LRESULT WINAPI SendMessageA(HWND, UINT, WPARAM, LPARAM);
DLLIMPORT HDC WINAPI BeginPaint(HWND, PAINTSTRUCT*);
DLLIMPORT BOOL WINAPI EndPaint(HWND, const PAINTSTRUCT*);
DLLIMPORT BOOL WINAPI GetClientRect(HWND, RECT*);
DLLIMPORT BOOL WINAPI InvalidateRect(HWND, const RECT*, BOOL);
DLLIMPORT BOOL WINAPI DestroyWindow(HWND);
DLLIMPORT UINT WINAPI SetTimer(HWND, UINT, UINT, void*);
DLLIMPORT BOOL WINAPI KillTimer(HWND, UINT);
DLLIMPORT HDC WINAPI GetDC(HWND);
DLLIMPORT int WINAPI ReleaseDC(HWND, HDC);
DLLIMPORT int WINAPI FillRect(HDC, const RECT*, HBRUSH);
DLLIMPORT HCURSOR WINAPI LoadCursorA(HINSTANCE, const char*);
DLLIMPORT int WINAPI GetSystemMetrics(int);
DLLIMPORT BOOL WINAPI SetWindowTextA(HWND, const char*);
// gdi32
DLLIMPORT HBRUSH WINAPI CreateSolidBrush(COLORREF);
DLLIMPORT HGDIOBJ WINAPI SelectObject(HDC, HGDIOBJ);
DLLIMPORT BOOL WINAPI DeleteObject(HGDIOBJ);
DLLIMPORT COLORREF WINAPI SetPixel(HDC, int, int, COLORREF);
DLLIMPORT COLORREF WINAPI GetPixel(HDC, int, int);
DLLIMPORT HGDIOBJ WINAPI GetStockObject(int);
DLLIMPORT BOOL WINAPI BitBlt(HDC, int, int, int, int, HDC, int, int, DWORD);
DLLIMPORT HDC WINAPI CreateCompatibleDC(HDC);
DLLIMPORT BOOL WINAPI DeleteDC(HDC);
DLLIMPORT HBITMAP WINAPI CreateDIBSection(HDC, const BITMAPINFO*, UINT, void**, HANDLE, DWORD);
DLLIMPORT BOOL WINAPI Rectangle(HDC, int, int, int, int);
DLLIMPORT BOOL WINAPI TextOutA(HDC, int, int, const char*, int);
DLLIMPORT int WINAPI GetDeviceCaps(HDC, int);
typedef HANDLE HFONT;
typedef struct { LONG cx, cy; } SIZE;
typedef struct { LONG tmHeight, tmAscent, tmDescent, tmInternalLeading, tmExternalLeading, tmAveCharWidth, tmMaxCharWidth, tmWeight, tmOverhang, tmDigitizedAspectX, tmDigitizedAspectY; BYTE tmFirstChar, tmLastChar, tmDefaultChar, tmBreakChar, tmItalic, tmUnderlined, tmStruckOut, tmPitchAndFamily, tmCharSet; } TEXTMETRICA;
DLLIMPORT HFONT WINAPI CreateFontA(int, int, int, int, int, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, const char*);
DLLIMPORT BOOL WINAPI GetTextMetricsA(HDC, TEXTMETRICA*);
DLLIMPORT BOOL WINAPI GetTextExtentPoint32A(HDC, const char*, int, SIZE*);
DLLIMPORT COLORREF WINAPI SetTextColor(HDC, COLORREF);
DLLIMPORT int WINAPI SetBkMode(HDC, int);
DLLIMPORT BOOL WINAPI GetCharWidth32A(HDC, UINT, UINT, int*);
DLLIMPORT int WINAPI DrawTextA(HDC, const char*, int, RECT*, UINT);
