// Pure-WebAssembly arctangent kernels for the JIT (FPATAN): atan2(y, x) with the semantics of
// JavaScript's Math.atan2 and atan(x) as a helper. No imports, no memory, no calls into JS (D004):
// everything lives in locals and immediate constants.
//
// Algorithm (all derived from the definitions; constants from tools/gen_atan_table.py):
//   1. NaN in either argument -> that NaN (y first). a = |y|, b = |x|.
//   2. Quadrant case q = (a > b) | signbit(x) << 1. t = min(a, b) / max(a, b) in [0, 1] (the ratio
//      is always the smaller over the larger: no overflow; underflow to 0/denormal is the correct
//      result). a == b == 0 -> t = 0 (atan2(±0, ±0) = ±0 / ±pi); a == b == inf -> t = 1 (±pi/4, ±3pi/4).
//   3. Table reduction: k = round(8 t) except k = 0 below 1/8, c = k/8, u = (t - c) / (1 + t c), so
//      atan(t) = atan(c) + atan(u) with |u| <= 1/8 (k = 0) or |u| <= 1/16 (k >= 1). t - c is exact
//      (Sterbenz: c/2 <= t <= 2c for k >= 1); the denominator and the quotient contribute ~2.5 ulp of
//      u, which is at most a third of the result for k >= 1 and absent for k = 0 (u = t).
//   4. atan(u) = u + u^3 P(u^2), P the Taylor series to u^17 (truncation < 3e-18 relative to u on
//      |u| <= 1/8); the u^3 P term is < u/192 so its rounding errors are negligible.
//   5. The quadrant constant is folded into the table: base(k, q) = atan(c) | pi/2 - atan(c) |
//      pi - atan(c) | pi/2 + atan(c) as a hi/lo double-double, and atan(u) is negated for q = 1, 2.
//      result = copysign(hi + (lo + ±atan(u)), y): a single final rounding after the exact base,
//      so pi - small and pi/2 ± small are accurate to the last bit of the table split (2^-106).
//   Error budget (relative to the exact value): ratio rounding <= 2^-53, u error <= 2.5 * 2^-53 / 3,
//   two roundings of the small part <= 2 * 2^-53 / 3, final rounding <= 2^-53: about 3.5 * 2^-53
//   ~ 3.9e-16 worst case, typically well under 2 ulp (measured in tests/fpmath-atan.test.js).
import { Code, T } from './wasm.js';

/**
 * Base angles hi/lo at index 4*k + q (k = 0..8, q = 0..3), generated by tools/gen_atan_table.py:
 * q = 0: atan(k/8), 1: pi/2 - atan(k/8), 2: pi - atan(k/8), 3: pi/2 + atan(k/8).
 * @type {ReadonlyArray<readonly [number, number]>}
 */
export const BASES = Object.freeze([
  // k = 0
  [0.0, 0.0], [1.5707963267948966, 6.123233995736766e-17], [3.141592653589793, 1.2246467991473532e-16], [1.5707963267948966, 6.123233995736766e-17],
  // k = 1: atan(1/8)
  [0.12435499454676144, -3.1253241424539383e-18], [1.446441332248135, 9.211323971545052e-17], [3.017237659043032, -6.869902525221314e-17], [1.695151321341658, 3.0351440199284805e-17],
  // k = 2: atan(2/8)
  [0.24497866312686414, 1.0698755618734451e-17], [1.3258176636680326, -8.824429373951136e-17], [2.896613990462929, 1.950326511428876e-16], [1.8157749899217608, -1.133563127078463e-17],
  // k = 3: atan(3/8)
  [0.35877067027057225, -2.4623815582638635e-17], [1.2120256565243244, 3.034500430874847e-17], [2.782821983319221, 9.157734426611613e-17], [1.9295669970654687, 9.211967560598685e-17],
  // k = 4: atan(4/8)
  [0.4636476090008061, 2.2698777452961687e-17], [1.1071487177940904, 9.40447137356638e-17], [2.677945044588987, 1.5527705369303147e-16], [2.0344439357957027, 2.841996617907152e-17],
  // k = 5: atan(5/8)
  [0.5585993153435624, -5.4556305485916264e-18], [1.0121970114513341, 6.668797050595929e-17], [2.5829933382462307, 1.2792031046332694e-16], [2.129395642138459, 5.577670940877603e-17],
  // k = 6: atan(6/8)
  [0.6435011087932844, 1.5834785051444286e-17], [0.9272952180016122, 4.5397554905923374e-17], [2.498091544796509, -4.392407599224622e-18], [2.214297435588181, 1.880894274713276e-16],
  // k = 7: atan(7/8)
  [0.7188299996216245, -2.1478388444456983e-17], [0.8519663271732721, -2.831157406069101e-17], [2.4227626539681686, 1.439430683591923e-16], [2.289626326416521, 3.975395151291068e-17],
  // k = 8: atan(1) = pi/4
  [0.7853981633974483, 3.061616997868383e-17], [0.7853981633974483, 3.061616997868383e-17], [2.356194490192345, 9.184850993605148e-17], [2.356194490192345, 9.184850993605148e-17],
]);

/** Taylor coefficients of P(v) = sum_{j=1..8} (-1)^j v^(j-1) / (2j+1): atan(u) = u + u^3 P(u^2). */
export const POLY = Object.freeze([-0.3333333333333333, 0.2, -0.14285714285714285, 0.1111111111111111, -0.09090909090909091, 0.07692307692307693, -0.06666666666666667, 0.058823529411764705]);

/**
 * Define the arctangent kernels in a module under construction. Nothing is exported; the caller
 * decides (m.exportFunc) or calls them by index.
 * @param {import('./wasm.js').ModuleBuilder} m
 * @returns {{ atan2: number, atan: number }} function indices:
 *   atan2(y: f64, x: f64) -> f64 : Math.atan2(y, x) semantics (signed zeros, infinities, NaN
 *     pass-through — y's NaN wins, extreme ratios);
 *   atan(x: f64) -> f64 : Math.atan(x) (= atan2(x, 1)).
 */
export function addAtanKernels(m) {
  // ---- atan2(y, x)
  const atan2 = (() => {
    const c = new Code();
    // params: 0 y, 1 x ; f64 locals: 2 a=|y|, 3 b=|x|, 4 t, 5 u, 6 v (=c then u^2), 7 hi, 8 lo, 9 p ;
    // i32 locals: 10 k, 11 q
    const [Y, X, A, B, TT, U, V, HI, LO, P, K, Q] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
    // NaN pass-through: y first, then x
    c.get(Y).get(Y).f64ne(); const ny = c.if_(); c.get(Y).return_(); c.end(); void ny;
    c.get(X).get(X).f64ne(); const nx = c.if_(); c.get(X).return_(); c.end(); void nx;
    c.get(Y).f64abs().set(A);
    c.get(X).f64abs().set(B);
    // q = (a > b) | signbit(x) << 1   (the sign bit, so that -0 counts as negative)
    c.get(A).get(B).f64gt().get(X).i64reinterpret_f64().i64(0).i64lt_s().i32(1).shl().or().set(Q);
    // t = a > b ? b / a : (b == 0 ? 0 : (a == b ? 1 : a / b))
    c.get(A).get(B).f64gt(); const tb = c.if_(T.f64);
    c.get(B).get(A).f64div();
    c.else_();
    c.f64c(0).f64c(1).get(A).get(B).f64div().get(A).get(B).f64eq().select().get(B).f64c(0).f64eq().select();
    c.end(); void tb;
    c.set(TT);
    // k = t < 1/8 ? 0 : trunc(8 t + 1/2)   (8 t exact; the +1/2 rounding only nudges a boundary by an ulp)
    c.i32(0).get(TT).f64c(8).f64mul().f64c(0.5).f64add().i32trunc_sat_f64_s().get(TT).f64c(0.125).f64lt().select().set(K);
    // c = k / 8 (exact) ; u = (t - c) / (1 + t c)  (k = 0: u = t / 1 exactly)
    c.get(K).f64convert_i32_s().f64c(0.125).f64mul().set(V);
    c.get(TT).get(V).f64sub().f64c(1).get(TT).get(V).f64mul().f64add().f64div().set(U);
    // u = -u for q = 1 (pi/2 - atan) and q = 2 (pi - atan): flip = (q ^ q >> 1) & 1
    c.get(U).f64neg().get(U).get(Q).get(Q).i32(1).shr_u().xor().i32(1).and().select().set(U);
    // p = P(v), v = u^2, Horner from the highest term
    c.get(U).get(U).f64mul().set(V);
    c.f64c(POLY[POLY.length - 1]);
    for (let j = POLY.length - 2; j >= 0; j--) c.get(V).f64mul().f64c(POLY[j]).f64add();
    c.set(P);
    // atan(u) = u + (u v) p
    c.get(U).get(U).get(V).f64mul().get(P).f64mul().f64add().set(P);
    // base angle (hi, lo) = BASES[4 k + q] via a jump table
    const done = c.block();
    const labels = [];
    for (let i = 0; i < BASES.length; i++) labels.push(c.block());
    c.get(K).i32(2).shl().get(Q).or().br_table(labels, done);
    for (let i = 0; i < BASES.length; i++) {
      c.end(); // closes the innermost remaining block = labels[BASES.length - 1 - i]
      const [hi, lo] = BASES[BASES.length - 1 - i];
      c.f64c(hi).set(HI).f64c(lo).set(LO).br(done);
    }
    c.end(); // done
    // copysign(hi + (lo + atan(u)), y)
    c.get(HI).get(LO).get(P).f64add().f64add().get(Y).f64copysign();
    return m.func([T.f64, T.f64], [T.f64], [T.f64, T.f64, T.f64, T.f64, T.f64, T.f64, T.f64, T.f64, T.i32, T.i32], c, 'atan2');
  })();

  // ---- atan(x) = atan2(x, 1)
  const atan = (() => {
    const c = new Code();
    c.get(0).f64c(1).call(atan2);
    return m.func([T.f64], [T.f64], [], c, 'atan');
  })();

  return { atan2, atan };
}
